{
  "hash": "fb3bf741050a5f87b364c2708635f8b3",
  "result": {
    "markdown": "---\ntitle: \"Estatística Descritiva e Inferencial - Testes\"\nformat: html\neditor: visual\nmessage: false\nwarning: false\n---\n\n\n## Estatística Descritiva e Estatística Inferencial\n\n## Pacotes\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-1_689ee5bab8e912df8a2cc5f27082feb3'}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(gsheet)\nlibrary(readxl)\nlibrary(report)\nlibrary(emmeans)\nlibrary(multcomp)\nlibrary(multcompView)\nlibrary(DHARMa)\nlibrary(performance)\nlibrary(agricolae)\nlibrary(car)\n#library(MASS)\n```\n:::\n\n\n### Estatística Descritiva\n\nA estatística descritiva pode ser resumida na qual organiza a coleta, a apuração e a descrição dos dados para amostras, sem almejar conclusões categóricas para as populações nas quais essas amostras se originaram.\n\n### Carregando o pacote de dados\n\nPacote de dados disponíveis em planilha no google drive.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-2_0d85a783d37e3a49f6b00f56619b9051'}\n\n```{.r .cell-code}\nmg <- gsheet2tbl(\"https://docs.google.com/spreadsheets/d/1bq2N19DcZdtax2fQW9OHSGMR0X2__Z9T/edit#gid=983033137\")\n\ntheme_set(theme_bw())\n\nmg\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 20 × 3\n   trat      rep  comp\n   <chr>   <dbl> <dbl>\n 1 Mg2         1   9  \n 2 Mg2         2  12.5\n 3 Mg2         3  10  \n 4 Mg2         4   8  \n 5 Mg2         5  13.2\n 6 Mg2         6  11  \n 7 Mg2         7  10.8\n 8 Mg2         8   9.5\n 9 Mg2         9  10.8\n10 Mg2        10  10.4\n11 control     1  13.7\n12 control     2  15.9\n13 control     3  15.7\n14 control     4  14.2\n15 control     5  15.9\n16 control     6  16.5\n17 control     7  18  \n18 control     8  14.4\n19 control     9  16.4\n20 control    10  16  \n```\n:::\n:::\n\n\n### Tratamentos independentes\n\nUm pesquisador conduziu um experimento com o objetivo de avaliar o efeito de um micronutriente, o magnésio (Mg), adicionado na solução do solo cultivado com plantas de arroz, no manejo de uma doença fúngica. O experimento foi conduzido em delineamento inteiramente casualizado com 10 repetições, sendo cada repetição um vaso de planta. Um dos tratamentos é o chamado controle, ou testemunha, sem o suplemento mineral. O segundo é aquele com o suplemento do Mg na dose de 2 mM. Em cada uma das repetições foi obtido um valor médio do comprimento de lesões em um determinado tempo após a inoculação.\n\nOs gráficos a seguir mostram que o incremento de magnésio reduz a severidade da doença, ou seja, induz a resistência. Visualmente indica que existe um efeito. Mas, uma hipótese científica deve ser testada.\n\nHipótese: o incremento de magnésio aumenta a resistência a doença;\n\nHipótese estatística: não existem diferenças entre os tratamentos.\n\nUsa-se o teste \"T\" para número de amostras igual ou inferior a 30. Usa-se o teste \"T\" para grupos independentes.\n\nPremissas: Teste de normalidade e variâncias homogêneas.\n\nPodemos assumir estas premissas através de uma análise exploratória, através da simetria do boxplot. Assume-se visualmente que as variâncias são iguais e que existe uma normalidade, mas, isso pode ser testado. Devemos primeiramente verificar as premissas.\n\nSe a distribuição não for normal, devemos realizar o teste não paramétrico, como o shapiro-wilk.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-3_2521535de8d47b21e86f68c0c5eb4927'}\n\n```{.r .cell-code}\nmg |> \n  ggplot(aes(trat, comp))+\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](Aula_06_07_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n## Teste estatístico\n\n### Teste \"T\" student\n\nO teste t compara duas médias e mostra se as diferenças entre essas médias são significativas. A necessidade de determinar se duas médias de amostras são diferentes entre si é uma situação extremamente frequente em pesquisas científicas. Como todo teste estatístico, o teste t também tem como produto a medida do p valor. Ou seja, calculamos a probabilidade da diferença encontrada (entre as médias) terem sido por acaso.\n\nÉ ideal que tenhamos os vetores separados em duas colunas, em formato largo. Para realizar essa conversão, faremos o seguite comando, atribuindo ao mg2.\n\nPrecisamos de uma coluna para cada tratamento.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-4_f8561ca063429ddb6cc163bddcc0062f'}\n\n```{.r .cell-code}\n?t.test\n\nmg2 <- mg |> \n  pivot_wider(names_from = trat,\n              values_from = comp)\n\nmg2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 10 × 3\n     rep   Mg2 control\n   <dbl> <dbl>   <dbl>\n 1     1   9      13.7\n 2     2  12.5    15.9\n 3     3  10      15.7\n 4     4   8      14.2\n 5     5  13.2    15.9\n 6     6  11      16.5\n 7     7  10.8    18  \n 8     8   9.5    14.4\n 9     9  10.8    16.4\n10    10  10.4    16  \n```\n:::\n:::\n\n\n### Realizando o teste T-student\n\nA primeira média (X) é referente ao tratamento mg2, que foi incluído primeiro na fórmula.\n\nEncontrou-se uma diferença, mesmo em uma probabilidade muito pequena.\n\nAté agora, assume-se que o teste T é confiável, existe uma diferença estatística.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-5_bb110ab877aa388a4c9468ac7e166f91'}\n\n```{.r .cell-code}\nteste1 <- t.test(mg2$Mg2, mg2$control)\n  teste1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  mg2$Mg2 and mg2$control\nt = -8.1549, df = 17.354, p-value = 2.423e-07\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n -6.490393 -3.825607\nsample estimates:\nmean of x mean of y \n   10.520    15.678 \n```\n:::\n:::\n\n\nVamos obter estatísticas que descrevem o conjunto, seja a tendência central ou a dispersão dos dados. No caso, será a média, variância, desvio padrão, erro padrão e intervalo de confiança - esse último para inferência visual.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-6_dea5b0d6e44b42de139aea8e174198fb'}\n\n```{.r .cell-code}\ndat2 <- mg |> \n  group_by(trat) |> \n  summarise(mean_comp = mean(comp),\n    sd_comp = sd(comp),\n    var_comp = var(comp),\n    n = n(),\n    se_comp = sd_comp / sqrt(n - 1),\n    ci = se_comp * qt(0.025, df = 9))\ndat2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 7\n  trat    mean_comp sd_comp var_comp     n se_comp     ci\n  <chr>       <dbl>   <dbl>    <dbl> <int>   <dbl>  <dbl>\n1 Mg2          10.5    1.54     2.39    10   0.515 -1.16 \n2 control      15.7    1.27     1.61    10   0.424 -0.958\n```\n:::\n:::\n\n\nJá podemos visualizar os dados com as estatísticas calculadas. Abaixo, as barras verticais representam o intervalo de confiança 95%.\n\n## Teste de normalidade\n\n### Shapiro wilk\n\nO Teste de Shapiro-Wilk tem como objetivo avaliar se uma distribuição é semelhante a uma [distribuição normal](https://www.blog.psicometriaonline.com.br/blog/distribuicao-normal/). A distribuição normal também pode ser chamada de gaussiana e sua forma assemelha-se a de um sino. Esse tipo de distribuição é muito importante, por ser frequentemente usada para modelar fenômenos naturais.\n\nSe o valor foi acima de 0,05, aceito que a distribuição é normal. Menor que 0,05 rejeita-se a hipótese nula, de que a distribuição não é normal.\n\nNeste caso, assume-se que a distribuição é normal.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-7_f25dee598751350bbdf8faedbeaa1b4e'}\n\n```{.r .cell-code}\nshapiro.test(mg2$control)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tShapiro-Wilk normality test\n\ndata:  mg2$control\nW = 0.93886, p-value = 0.5404\n```\n:::\n:::\n\n\nHistograma para observação de normalidade.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-8_852aa9918d6b44324423f9513dc3b509'}\n\n```{.r .cell-code}\nhist(mg2$control)\n```\n\n::: {.cell-output-display}\n![](Aula_06_07_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-9_83d99c83437783c9909b40df1994ed54'}\n\n```{.r .cell-code}\nhist(mg2$Mg2)\n```\n\n::: {.cell-output-display}\n![](Aula_06_07_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-10_fa2db374fbec9bbbcff8c262d2a87665'}\n\n```{.r .cell-code}\nshapiro.test(mg2$Mg2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tShapiro-Wilk normality test\n\ndata:  mg2$Mg2\nW = 0.97269, p-value = 0.9146\n```\n:::\n:::\n\n\nPara comparar variâncias.\n\nPosso assumir como variáveis homogêneas, valor de P mostrou-se alto. Podemos continuar normalmente com o teste T.\n\nVerificaram-se as premissas de normalidade e de variância.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-11_d19af0daa823a51eac30a451b7eb8f53'}\n\n```{.r .cell-code}\nvar.test(mg2$control, mg2$Mg2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tF test to compare two variances\n\ndata:  mg2$control and mg2$Mg2\nF = 0.67654, num df = 9, denom df = 9, p-value = 0.5698\nalternative hypothesis: true ratio of variances is not equal to 1\n95 percent confidence interval:\n 0.1680428 2.7237436\nsample estimates:\nratio of variances \n         0.6765394 \n```\n:::\n:::\n\n\nAssumindo a variância como verdadeira, informando-a como homogênea.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-12_81c938d7cb8d39b6b9ff8d5710b531cc'}\n\n```{.r .cell-code}\nvar.test(mg2$control, mg2$Mg2, \n         var.equal = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tF test to compare two variances\n\ndata:  mg2$control and mg2$Mg2\nF = 0.67654, num df = 9, denom df = 9, p-value = 0.5698\nalternative hypothesis: true ratio of variances is not equal to 1\n95 percent confidence interval:\n 0.1680428 2.7237436\nsample estimates:\nratio of variances \n         0.6765394 \n```\n:::\n:::\n\n\nQuanto mais próximos os pontos estão da linha, indicam maior normalidade das variâncias. Isso quer dizer que as resultados dentro de cada grupo foram semelhantes.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-13_04746e39bd82eaaeea6c15115db4e7f4'}\n\n```{.r .cell-code}\nqqnorm(mg2$control)\nqqline(mg2$control)\n```\n\n::: {.cell-output-display}\n![](Aula_06_07_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n### Report\n\nMonta um texto base que pode ser usado no artigo.\n\n\"Effect sizes were labelled following Cohen's (1988) recommendations. The Welch Two Sample t-test testing the difference between mg2\\$Mg2 and mg2\\$control (mean of x = 10.52, mean of y = 15.68) suggests that the effect is negative, statistically significant, and large (difference = -5.16, 95% CI \\[-6.49, -3.83\\], t(17.35) = -8.15, p \\< .001.\"\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-14_56bc7ee529f9841bac2bb08e1cdbc882'}\n\n```{.r .cell-code}\nreport(teste1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nEffect sizes were labelled following Cohen's (1988) recommendations.\n\nThe Welch Two Sample t-test testing the difference between mg2$Mg2 and\nmg2$control (mean of x = 10.52, mean of y = 15.68) suggests that the effect is\nnegative, statistically significant, and large (difference = -5.16, 95% CI\n[-6.49, -3.83], t(17.35) = -8.15, p < .001; Cohen's d = -3.65, 95% CI [-5.12,\n-2.14])\n```\n:::\n:::\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-15_2dc975a5c205ae9efd665489b30f97c5'}\n\n```{.r .cell-code}\nwilcox.test(mg2$control, mg2$Mg2, \n         paired = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWilcoxon rank sum test with continuity correction\n\ndata:  mg2$control and mg2$Mg2\nW = 100, p-value = 0.0001817\nalternative hypothesis: true location shift is not equal to 0\n```\n:::\n:::\n\n\n## Dois grupos dependentes\n\nOcorre uma dependência do avaliador, pois ocorre a avaliação com e sem a escala diagramática, ou seja, existe dependência.\n\nComo são dois grupos, usa-se o teste T, mas devemos indicar a dependência. Uso de um teste pareado, diferente do exemplo anterior.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-16_78c94ef2adee376b2dbc59c4f0dfdbd7'}\n\n```{.r .cell-code}\nescala <- gsheet2tbl(\"https://docs.google.com/spreadsheets/d/1aID5Dh6PlBVCKzU1j7k-WA6zuWQWE2NhtWEgdJtt5iA/edit#gid=1139290215\")\n\nescala\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 20 × 7\n   assessment rater acuracia precisao vies_geral vies_sistematico vies_constante\n   <chr>      <chr>    <dbl>    <dbl>      <dbl>            <dbl>          <dbl>\n 1 Unaided    A         0.81     0.83       0.98             1.19           0.11\n 2 Unaided    B         0.72     0.73       0.99             0.92          -0.11\n 3 Unaided    C         0.56     0.71       0.78             1.16           0.73\n 4 Unaided    D         0.82     0.82       1                0.95          -0.01\n 5 Unaided    E         0.75     0.75       0.99             1.1            0.07\n 6 Unaided    F         0.69     0.75       0.92             0.8            0.34\n 7 Unaided    G         0.81     0.82       0.98             1.16           0.13\n 8 Unaided    H         0.78     0.87       0.9              1.07          -0.47\n 9 Unaided    I         0.78     0.79       0.99             1.14           0.09\n10 Unaided    J         0.62     0.83       0.74             0.65          -0.72\n11 Aided1     A         0.91     0.95       0.96             0.89          -0.28\n12 Aided1     B         0.91     0.96       0.95             0.89          -0.3 \n13 Aided1     C         0.91     0.96       0.95             1.28           0.21\n14 Aided1     D         0.96     0.97       0.99             1.14           0.09\n15 Aided1     E         0.96     0.96       1                1             -0.1 \n16 Aided1     F         0.9      0.97       0.93             0.86          -0.36\n17 Aided1     G         0.85     0.95       0.89             0.83          -0.45\n18 Aided1     H         0.88     0.97       0.9              1.29           0.38\n19 Aided1     I         0.95     0.96       0.99             1.14           0.07\n20 Aided1     J         0.94     0.96       0.99             0.91          -0.13\n```\n:::\n:::\n\n\nMostrando a acurácia com e sem o auxílio da escala avaliadora.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-17_271c767f0fcb76e5027cdcdc0f7af9c9'}\n\n```{.r .cell-code}\nescala |> \n  ggplot(aes(assessment, acuracia))+\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](Aula_06_07_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n#### Teste T para a acurácia.\n\nPrimeiro passar do formato longo para o formato largo, selecionando na escala 2 apenas os valores de interesse.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-18_d168cafa75728127c734a9b8e4f2a4c2'}\n\n```{.r .cell-code}\nescala2 <- escala |> \n  dplyr::select(assessment, rater,acuracia) |> \n  pivot_wider(names_from = assessment,\n              values_from = acuracia)\n  \nescala2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 10 × 3\n   rater Unaided Aided1\n   <chr>   <dbl>  <dbl>\n 1 A        0.81   0.91\n 2 B        0.72   0.91\n 3 C        0.56   0.91\n 4 D        0.82   0.96\n 5 E        0.75   0.96\n 6 F        0.69   0.9 \n 7 G        0.81   0.85\n 8 H        0.78   0.88\n 9 I        0.78   0.95\n10 J        0.62   0.94\n```\n:::\n:::\n\n\n#### Teste shapiro wilk\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-19_59d2bcf2810a283a5ff6655b2b5f4c32'}\n\n```{.r .cell-code}\nshapiro.test(escala2$Unaided)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tShapiro-Wilk normality test\n\ndata:  escala2$Unaided\nW = 0.87881, p-value = 0.1265\n```\n:::\n\n```{.r .cell-code}\nshapiro.test(escala2$Aided1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tShapiro-Wilk normality test\n\ndata:  escala2$Aided1\nW = 0.92852, p-value = 0.4335\n```\n:::\n:::\n\n\nTeste de variância.\n\nRejeita-se H0 por p valor ser menor que 0,05.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-20_89c5d214535fe588efea7651c1efa5de'}\n\n```{.r .cell-code}\nvar.test(escala2$Unaided, escala2$Aided1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tF test to compare two variances\n\ndata:  escala2$Unaided and escala2$Aided1\nF = 5.9294, num df = 9, denom df = 9, p-value = 0.0141\nalternative hypothesis: true ratio of variances is not equal to 1\n95 percent confidence interval:\n  1.472772 23.871614\nsample estimates:\nratio of variances \n          5.929371 \n```\n:::\n:::\n\n\nO teste pareado dá a diferença entre os dados diferentes. O teste T foi usado porque a distribuição é normal.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-21_8b7f815d4ffd8fb31d76e268bf702fee'}\n\n```{.r .cell-code}\nt.test(escala2$Aided1, escala2$Unaided,\n       paired = TRUE,\n       var.equal = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPaired t-test\n\ndata:  escala2$Aided1 and escala2$Unaided\nt = 5.9755, df = 9, p-value = 0.0002087\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n 0.1137215 0.2522785\nsample estimates:\nmean difference \n          0.183 \n```\n:::\n:::\n\n\n### Teste não paramétrico\n\nValores da tabela foram alterados para obtermos um novo boxplot.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-22_a1dc762e6a26f2b4e88774d260c8ec09'}\n\n```{.r .cell-code}\nescala <- gsheet2tbl(\"https://docs.google.com/spreadsheets/d/1bq2N19DcZdtax2fQW9OHSGMR0X2__Z9T/edit#gid=1729131173\")\n\nescala\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 20 × 7\n   assessment rater acuracia precisao vies_geral vies_sistematico vies_constante\n   <chr>      <chr>    <dbl>    <dbl>      <dbl>            <dbl>          <dbl>\n 1 Unaided    A         0.81     0.83       0.98             1.19           0.11\n 2 Unaided    B         0.72     0.73       0.99             0.92          -0.11\n 3 Unaided    C         0.4      0.71       0.78             1.16           0.73\n 4 Unaided    D         0.82     0.82       1                0.95          -0.01\n 5 Unaided    E         0.75     0.75       0.99             1.1            0.07\n 6 Unaided    F         0.45     0.75       0.92             0.8            0.34\n 7 Unaided    G         0.81     0.82       0.98             1.16           0.13\n 8 Unaided    H         0.78     0.87       0.9              1.07          -0.47\n 9 Unaided    I         0.78     0.79       0.99             1.14           0.09\n10 Unaided    J         0.5      0.83       0.74             0.65          -0.72\n11 Aided1     A         0.91     0.95       0.96             0.89          -0.28\n12 Aided1     B         0.91     0.96       0.95             0.89          -0.3 \n13 Aided1     C         0.91     0.96       0.95             1.28           0.21\n14 Aided1     D         0.96     0.97       0.99             1.14           0.09\n15 Aided1     E         0.96     0.96       1                1             -0.1 \n16 Aided1     F         0.9      0.97       0.93             0.86          -0.36\n17 Aided1     G         0.85     0.95       0.89             0.83          -0.45\n18 Aided1     H         0.88     0.97       0.9              1.29           0.38\n19 Aided1     I         0.95     0.96       0.99             1.14           0.07\n20 Aided1     J         0.94     0.96       0.99             0.91          -0.13\n```\n:::\n:::\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-23_f742fb50ca6a3f36fd0f43b7ffdad55c'}\n\n```{.r .cell-code}\nescala |> \n  ggplot(aes(assessment, acuracia))+\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](Aula_06_07_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n#### Teste wilcox\n\nConclui com base no valor de P. Rejeita-se a hipótese nula, pois os valores são diferentes. Ele corrobora com o teste T.\n\nQuando os dados são pareados, usamos \"paired = TRUE\", quando os não são pareados, usamos \"paired = FALSE\".\n\nSe as variâncias são heterogêneas, assumimos que \"var.equal = FALSE\".\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-24_436d047bc0811a28836e6ccda3261f9d'}\n\n```{.r .cell-code}\nwilcox.test(escala2$Aided1,\n            escala2$Unaided,\n            paired = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWilcoxon signed rank test with continuity correction\n\ndata:  escala2$Aided1 and escala2$Unaided\nV = 55, p-value = 0.005889\nalternative hypothesis: true location shift is not equal to 0\n```\n:::\n:::\n\n\nTeste shapiro wilk para observar normalidade.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-25_e838d8ef04ac218f0bd3549c0c1e4ce3'}\n\n```{.r .cell-code}\nshapiro.test(escala2$Unaided)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tShapiro-Wilk normality test\n\ndata:  escala2$Unaided\nW = 0.87881, p-value = 0.1265\n```\n:::\n\n```{.r .cell-code}\nshapiro.test(escala2$Aided1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tShapiro-Wilk normality test\n\ndata:  escala2$Aided1\nW = 0.92852, p-value = 0.4335\n```\n:::\n:::\n\n\n## Teste de comparação de médias\n\nEstudando o conjunto de dados \"micelial\"\n\nH0 = Pelo menos uma das médias é diferente das demais.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-26_da7cf6a280d80b22de1ab30d566bab5d'}\n\n```{.r .cell-code}\nmicelial <- gsheet2tbl(\"https://docs.google.com/spreadsheets/d/1bq2N19DcZdtax2fQW9OHSGMR0X2__Z9T/edit#gid=959387827\")\n\nmicelial\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 30 × 3\n   especie   rep   tcm\n   <chr>   <dbl> <dbl>\n 1 Fasi        1  1.5 \n 2 Fasi        2  1.59\n 3 Fasi        3  1.52\n 4 Fasi        4  1.52\n 5 Fasi        5  1.6 \n 6 Fasi        6  1.7 \n 7 Faus        1  1.52\n 8 Faus        2  1.25\n 9 Faus        3  1.27\n10 Faus        4  1.3 \n# ℹ 20 more rows\n```\n:::\n:::\n\n\nGráfico jitter para explorar melhor o conjunto de dados.\n\nO que a ANOVA vai testar? Se existe pelo menos uma média que é diferente das outras médias. Ele testa no grupo e entre cada grupo.\n\nA ANOVA vai comparar as médias de 3 ou mais grupos.\n\nCom o gráfico a seguir, não é possível observar visualmente se há ou não diferença entre as médias das espécies. A distribuição não é homogênea.\n\nA variabilidade dentro de cada grupo é grande.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-27_a858baf66e7a5a48e55110a35ad1d3a2'}\n\n```{.r .cell-code}\nmicelial |> \n  ggplot(aes(especie, tcm))+\n  geom_jitter(width = 0.05)\n```\n\n::: {.cell-output-display}\n![](Aula_06_07_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\nTeste de ANOVA as cegas, sem testar premissas. Através do \"aov\".\n\nSe as médias não diferem, não faz mais sentido continuar o teste de comparação de médias.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-28_145464c465848bc6cda998ae4766935b'}\n\n```{.r .cell-code}\nanova1 <- aov(tcm ~ especie, data = micelial)\n\nanova(anova1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Variance Table\n\nResponse: tcm\n          Df  Sum Sq Mean Sq F value    Pr(>F)    \nespecie    4 1.46958 0.36739  19.629 2.028e-07 ***\nResiduals 25 0.46792 0.01872                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\nTeste de ANOVA as cegas, sem testar premissas. Através do \"lm\". Adicionando o \"-1\" após a espécie, eu encontro diretamente as médias.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-29_f1588e0cfe663de67a7aa191b1f6adc9'}\n\n```{.r .cell-code}\nm1 <- lm(tcm ~ especie -1, data = micelial)\n\nanova(m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Variance Table\n\nResponse: tcm\n          Df Sum Sq Mean Sq F value    Pr(>F)    \nespecie    5 51.677 10.3354   552.2 < 2.2e-16 ***\nResiduals 25  0.468  0.0187                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\nNão existe diferença entre os resultados dos comandos \"aov\" e \"lm\". Dar preferência ao \"lm\".\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-30_08d9f620f029563a703c0beb6aad7018'}\n\n```{.r .cell-code}\nsummary(m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = tcm ~ especie - 1, data = micelial)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.23667 -0.09667  0.01583  0.08833  0.28333 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \nespecieFasi  1.57167    0.05585   28.14  < 2e-16 ***\nespecieFaus  1.23667    0.05585   22.14  < 2e-16 ***\nespecieFcor  1.32167    0.05585   23.66  < 2e-16 ***\nespecieFgra  0.91167    0.05585   16.32 7.66e-15 ***\nespecieFmer  1.42667    0.05585   25.54  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1368 on 25 degrees of freedom\nMultiple R-squared:  0.991,\tAdjusted R-squared:  0.9892 \nF-statistic: 552.2 on 5 and 25 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nRemovendo um pouco das variabilidades do conjunto, obtemos a tabela a seguir.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-31_ba4e8044adc9b2d0136c69054956a0e2'}\n\n```{.r .cell-code}\nmicelial1 <- gsheet2tbl(\"https://docs.google.com/spreadsheets/d/1bq2N19DcZdtax2fQW9OHSGMR0X2__Z9T/edit#gid=959387827\")\n```\n:::\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-32_9da1197cf48d77596491eaee49ac8cfe'}\n\n```{.r .cell-code}\nmicelial1 |> \n  ggplot(aes(especie, tcm))+\n  geom_jitter(width = 0.05)\n```\n\n::: {.cell-output-display}\n![](Aula_06_07_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\nAgora, parece haver alguma diferença entre as médias. Rodaremos os testes.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-33_861e85f8afd2109b63464ff3e7835d71'}\n\n```{.r .cell-code}\nm1 <- lm(tcm ~ especie -1, data = micelial1)\n\nanova(m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Variance Table\n\nResponse: tcm\n          Df Sum Sq Mean Sq F value    Pr(>F)    \nespecie    5 51.677 10.3354   552.2 < 2.2e-16 ***\nResiduals 25  0.468  0.0187                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-34_e86ae7df3d00912ec16bdad7534400b5'}\n\n```{.r .cell-code}\nsummary(m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = tcm ~ especie - 1, data = micelial1)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.23667 -0.09667  0.01583  0.08833  0.28333 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \nespecieFasi  1.57167    0.05585   28.14  < 2e-16 ***\nespecieFaus  1.23667    0.05585   22.14  < 2e-16 ***\nespecieFcor  1.32167    0.05585   23.66  < 2e-16 ***\nespecieFgra  0.91167    0.05585   16.32 7.66e-15 ***\nespecieFmer  1.42667    0.05585   25.54  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1368 on 25 degrees of freedom\nMultiple R-squared:  0.991,\tAdjusted R-squared:  0.9892 \nF-statistic: 552.2 on 5 and 25 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nO Emmeans define as médias diretamente.\n\nDefinindo um teste estatístico para comparação do crescimento.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-35_bebf60fda6ffbab9bba10239df09f49f'}\n\n```{.r .cell-code}\nmedias1 <- emmeans(m1, ~ especie)\n\nmedias1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n especie emmean     SE df lower.CL upper.CL\n Fasi     1.572 0.0559 25    1.457     1.69\n Faus     1.237 0.0559 25    1.122     1.35\n Fcor     1.322 0.0559 25    1.207     1.44\n Fgra     0.912 0.0559 25    0.797     1.03\n Fmer     1.427 0.0559 25    1.312     1.54\n\nConfidence level used: 0.95 \n```\n:::\n:::\n\n\nPara adicionar as letras, ou números correspondentes que indicam a diferença, usar o pacote multcomp e multcompview.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-36_99504759de1432cb0d41dec79bd7b36e'}\n\n```{.r .cell-code}\ncld(medias1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n especie emmean     SE df lower.CL upper.CL .group\n Fgra     0.912 0.0559 25    0.797     1.03  1    \n Faus     1.237 0.0559 25    1.122     1.35   2   \n Fcor     1.322 0.0559 25    1.207     1.44   2   \n Fmer     1.427 0.0559 25    1.312     1.54   23  \n Fasi     1.572 0.0559 25    1.457     1.69    3  \n\nConfidence level used: 0.95 \nP value adjustment: tukey method for comparing a family of 5 estimates \nsignificance level used: alpha = 0.05 \nNOTE: If two or more means share the same grouping symbol,\n      then we cannot show them to be different.\n      But we also did not show them to be the same. \n```\n:::\n:::\n\n\nComo saber se o modelo é confiável ou se preciso realizar conversões.\n\nRealizando a análise de normalidade dos resíduos.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-37_772e43dce4f4c55fbd2d39d515df6522'}\n\n```{.r .cell-code}\nhist(m1$residuals)\n```\n\n::: {.cell-output-display}\n![](Aula_06_07_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n:::\n\n\nO teste de shapiro executado indica normalidade dos resíduos. P valor = 0,8782. Não rejeita a hipótese.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-38_fbdb9b7c46e36e3d95f0a269f10d00fe'}\n\n```{.r .cell-code}\nshapiro.test(m1$residuals)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tShapiro-Wilk normality test\n\ndata:  m1$residuals\nW = 0.9821, p-value = 0.8782\n```\n:::\n:::\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-39_b714e9b270f5800a5c45e98b92507eda'}\n\n```{.r .cell-code}\nbartlett.test(tcm ~ especie, data = micelial1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tBartlett test of homogeneity of variances\n\ndata:  tcm by especie\nBartlett's K-squared = 4.4367, df = 4, p-value = 0.3501\n```\n:::\n:::\n\n\nPlot de diagnóstico dos resíduos.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-40_7c9bcb918ed332b384a18d9ecdfc41ed'}\n\n```{.r .cell-code}\nplot(simulateResiduals(m1))\n```\n\n::: {.cell-output-display}\n![](Aula_06_07_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n:::\n\n\nPossibilidade para conferir as premissas.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-41_d2ccc7ed4f37e5cc90273a5d79305d16'}\n\n```{.r .cell-code}\ncheck_normality(m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nOK: residuals appear as normally distributed (p = 0.878).\n```\n:::\n\n```{.r .cell-code}\ncheck_heteroscedasticity(m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nOK: Error variance appears to be homoscedastic (p = 0.880).\n```\n:::\n:::\n\n\nAnálise dos resíduos.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-42_0b6800f8251f44dbd23f83aaf10fe1c7'}\n\n```{.r .cell-code}\ncheck_model(m1)\n```\n\n::: {.cell-output-display}\n![](Aula_06_07_files/figure-html/unnamed-chunk-42-1.png){width=672}\n:::\n:::\n\n\n# AULA 07 - 24/04/2024\n\nContinuação da aula anterior\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-43_5342804a9d1e025758d5086b51bb75df'}\n\n```{.r .cell-code}\ninseticida <- InsectSprays\ninseticida |> \n  count(spray)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  spray  n\n1     A 12\n2     B 12\n3     C 12\n4     D 12\n5     E 12\n6     F 12\n```\n:::\n:::\n\n\nComo só temos um fator, a ANOVA neste caso seria unifatorial, com 6 níveis.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-44_dd53ac65ef18e8b9f3db3f350ad35ca3'}\n\n```{.r .cell-code}\ninseticida |> \n  ggplot(aes(spray, count))+\n  geom_boxplot()+\n  geom_jitter()+\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](Aula_06_07_files/figure-html/unnamed-chunk-44-1.png){width=672}\n:::\n:::\n\n\nObservando os box, podemos inferir que as variâncias são heterogêneas. Tratamento com maior variabilidade (F), com menos variabilidade (C) e que possui outlier.\n\nO modelo de ANOVA é ajustado, e trabalhamos com os resíduos da ANOVA, e não com os dados originais, e aí são aplicados os testes.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-45_ab3e91c0c72579403119d676c081f581'}\n\n```{.r .cell-code}\nm1 <- lm(count ~ spray,\n         data = inseticida)\nm1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = count ~ spray, data = inseticida)\n\nCoefficients:\n(Intercept)       sprayB       sprayC       sprayD       sprayE       sprayF  \n    14.5000       0.8333     -12.4167      -9.5833     -11.0000       2.1667  \n```\n:::\n:::\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-46_9fff7b7e312179a6eb781f248b4d3d2e'}\n\n```{.r .cell-code}\nsummary(m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = count ~ spray, data = inseticida)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-8.333 -1.958 -0.500  1.667  9.333 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  14.5000     1.1322  12.807  < 2e-16 ***\nsprayB        0.8333     1.6011   0.520    0.604    \nsprayC      -12.4167     1.6011  -7.755 7.27e-11 ***\nsprayD       -9.5833     1.6011  -5.985 9.82e-08 ***\nsprayE      -11.0000     1.6011  -6.870 2.75e-09 ***\nsprayF        2.1667     1.6011   1.353    0.181    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.922 on 66 degrees of freedom\nMultiple R-squared:  0.7244,\tAdjusted R-squared:  0.7036 \nF-statistic:  34.7 on 5 and 66 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-47_5bb0e8cf8e769347e110b7fffbda502a'}\n\n```{.r .cell-code}\nanova(m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Variance Table\n\nResponse: count\n          Df Sum Sq Mean Sq F value    Pr(>F)    \nspray      5 2668.8  533.77  34.702 < 2.2e-16 ***\nResiduals 66 1015.2   15.38                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-48_555a2eb9104afb1ea890217d8fa85de2'}\n\n```{.r .cell-code}\nhist(m1$residuals)\n```\n\n::: {.cell-output-display}\n![](Aula_06_07_files/figure-html/unnamed-chunk-48-1.png){width=672}\n:::\n:::\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-49_531c4128ea569db4add7bdb6c4456605'}\n\n```{.r .cell-code}\nshapiro.test(m1$residuals)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tShapiro-Wilk normality test\n\ndata:  m1$residuals\nW = 0.96006, p-value = 0.02226\n```\n:::\n:::\n\n\nO h0 deste teste sugere que é normal. O Pvalor deste teste indica que é\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-50_75d98256b6597b04c328c66642ce9e0c'}\n\n```{.r .cell-code}\nqqnorm(m1$residuals)\nqqline(m1$residuals)\n```\n\n::: {.cell-output-display}\n![](Aula_06_07_files/figure-html/unnamed-chunk-50-1.png){width=672}\n:::\n:::\n\n\nQuando os pontos acompanham a linha de tendência central, acusa que os dados são normais.\n\nPremissa importante: tem maior peso na decisão - homocedasticidade.\n\n### Barlett Test\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-51_6aeb5083a52e5d656e38f64f27d8c8ee'}\n\n```{.r .cell-code}\nbartlett.test(count ~ spray,\n              data = inseticida)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tBartlett test of homogeneity of variances\n\ndata:  count by spray\nBartlett's K-squared = 25.96, df = 5, p-value = 9.085e-05\n```\n:::\n:::\n\n\nPara testar a normalidade.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-52_0fbc21a447223ad18d58895f8ddf1f86'}\n\n```{.r .cell-code}\ncheck_normality(m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nWarning: Non-normality of residuals detected (p = 0.022).\n```\n:::\n:::\n\n\nPara testar heterocedasticidade.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-53_996bf1fbfeb57bebbf58d0e5e4385cf3'}\n\n```{.r .cell-code}\ncheck_heteroscedasticity(m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nWarning: Heteroscedasticity (non-constant error variance) detected (p < .001).\n```\n:::\n:::\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-54_a0be837999b2511b6f31b589f2f86c18'}\n\n```{.r .cell-code}\nplot(simulateResiduals(m1))\n```\n\n::: {.cell-output-display}\n![](Aula_06_07_files/figure-html/unnamed-chunk-54-1.png){width=672}\n:::\n:::\n\n\nTransformação de dados:\n\n-   Extrair a raiz quadrada (apropriada pra dados de contagem);\n\n-   Outros métodos (procurar).\n\n### Alternativa 01 - Extração da Raiz quadrada\n\nAlternativa 01 - transformação\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-55_9ac26483f06e44b20d1d43e4825e0884'}\n\n```{.r .cell-code}\ninseticida <-  inseticida |> \n  mutate(count2 = sqrt(count))\n\ninseticida |> \n  ggplot(aes(spray, count2))+\n  geom_boxplot()+\n  geom_jitter()+\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](Aula_06_07_files/figure-html/unnamed-chunk-55-1.png){width=672}\n:::\n:::\n\n\nA normalidade não é um problema aqui, e sim a variância.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-56_57fc5298789d1f4357b2e7fc639a5730'}\n\n```{.r .cell-code}\nm2 <- lm(count2 ~ spray, \n         data = inseticida)\nm2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = count2 ~ spray, data = inseticida)\n\nCoefficients:\n(Intercept)       sprayB       sprayC       sprayD       sprayE       sprayF  \n     3.7607       0.1160      -2.5158      -1.5963      -1.9512       0.2579  \n```\n:::\n\n```{.r .cell-code}\ncheck_normality(m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nOK: residuals appear as normally distributed (p = 0.681).\n```\n:::\n\n```{.r .cell-code}\ncheck_homogeneity(m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nOK: There is not clear evidence for different variances across groups (Bartlett Test, p = 0.586).\n```\n:::\n:::\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-57_b775f38dc1459ec1256e7a85e62e85ad'}\n\n```{.r .cell-code}\nanova(m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Variance Table\n\nResponse: count2\n          Df Sum Sq Mean Sq F value    Pr(>F)    \nspray      5 88.438 17.6876  44.799 < 2.2e-16 ***\nResiduals 66 26.058  0.3948                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-58_ea614a66b565fcc8425e4668130b8502'}\n\n```{.r .cell-code}\nhist(m2$residuals)\n```\n\n::: {.cell-output-display}\n![](Aula_06_07_files/figure-html/unnamed-chunk-58-1.png){width=672}\n:::\n:::\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-59_59764234fba4b11d38661c1c61e8f5e4'}\n\n```{.r .cell-code}\nsummary(m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = count2 ~ spray, data = inseticida)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.24486 -0.39970 -0.01902  0.42661  1.40089 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   3.7607     0.1814  20.733  < 2e-16 ***\nsprayB        0.1160     0.2565   0.452    0.653    \nsprayC       -2.5158     0.2565  -9.807 1.64e-14 ***\nsprayD       -1.5963     0.2565  -6.223 3.80e-08 ***\nsprayE       -1.9512     0.2565  -7.606 1.34e-10 ***\nsprayF        0.2579     0.2565   1.006    0.318    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.6283 on 66 degrees of freedom\nMultiple R-squared:  0.7724,\tAdjusted R-squared:  0.7552 \nF-statistic:  44.8 on 5 and 66 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-60_61d7e8639aa81ca8d5f1690e05cd5a54'}\n\n```{.r .cell-code}\nqqnorm(m2$residuals)\nqqline(m2$residuals)\n```\n\n::: {.cell-output-display}\n![](Aula_06_07_files/figure-html/unnamed-chunk-60-1.png){width=672}\n:::\n:::\n\n\nDe acordo com o plot, é possível inferenciar que os problemas de normalidade foram resolvidos.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-61_0cf8ffc576ef870eb4436191eb5a3e08'}\n\n```{.r .cell-code}\nshapiro.test(m2$residuals)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tShapiro-Wilk normality test\n\ndata:  m2$residuals\nW = 0.98721, p-value = 0.6814\n```\n:::\n:::\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-62_86ca31e7d477c25ae1b25281e5b0a7e6'}\n\n```{.r .cell-code}\nbartlett.test(count2 ~ spray,\n              data =inseticida)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tBartlett test of homogeneity of variances\n\ndata:  count2 by spray\nBartlett's K-squared = 3.7525, df = 5, p-value = 0.5856\n```\n:::\n:::\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-63_101547330666e1e2fb606688de98e4b9'}\n\n```{.r .cell-code}\ncheck_normality(m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nOK: residuals appear as normally distributed (p = 0.681).\n```\n:::\n:::\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-64_19373ee9819155b749a7d05b0ee80c85'}\n\n```{.r .cell-code}\ncheck_heteroscedasticity(m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nOK: Error variance appears to be homoscedastic (p = 0.854).\n```\n:::\n:::\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-65_5232c38a1e1c0cfd23bb71a5f5e3ec62'}\n\n```{.r .cell-code}\nplot(simulateResiduals(m2))\n```\n\n::: {.cell-output-display}\n![](Aula_06_07_files/figure-html/unnamed-chunk-65-1.png){width=672}\n:::\n:::\n\n\nÉ possível observar que a transformação dos dados resolveu a dispersão das variâncias. Podemos continuar com o teste. O resultado foi não significativo.\n\nPodemos seguir com a estimativa das médias.\n\nA ANOVA é um teste mais robusto à falta de normalidade do que à falta de homocedasticidade.\n\nLevene test - undefined\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-66_06dc0582b4d9b5a0232d76cf6603590a'}\n\n```{.r .cell-code}\nm1_medias <- emmeans(m1, ~spray)\nplot(m1_medias)\n```\n\n::: {.cell-output-display}\n![](Aula_06_07_files/figure-html/unnamed-chunk-66-1.png){width=672}\n:::\n:::\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-67_ee466ee753a08b67f14941e083ed1376'}\n\n```{.r .cell-code}\ncld(m1_medias)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n spray emmean   SE df lower.CL upper.CL .group\n C       2.08 1.13 66   -0.177     4.34  1    \n E       3.50 1.13 66    1.240     5.76  1    \n D       4.92 1.13 66    2.656     7.18  1    \n A      14.50 1.13 66   12.240    16.76   2   \n B      15.33 1.13 66   13.073    17.59   2   \n F      16.67 1.13 66   14.406    18.93   2   \n\nConfidence level used: 0.95 \nP value adjustment: tukey method for comparing a family of 6 estimates \nsignificance level used: alpha = 0.05 \nNOTE: If two or more means share the same grouping symbol,\n      then we cannot show them to be different.\n      But we also did not show them to be the same. \n```\n:::\n:::\n\n\nAgora, para o conjunto de dados transformados.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-68_0b5d36ab249cb227cf86f874e945c8c5'}\n\n```{.r .cell-code}\nm2_medias <- emmeans(m2, ~spray)\nplot(m2_medias)\n```\n\n::: {.cell-output-display}\n![](Aula_06_07_files/figure-html/unnamed-chunk-68-1.png){width=672}\n:::\n:::\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-69_9e9fbf9dc6f83b9904f057a4078776c2'}\n\n```{.r .cell-code}\ncld(m2_medias)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n spray emmean    SE df lower.CL upper.CL .group\n C       1.24 0.181 66    0.883     1.61  1    \n E       1.81 0.181 66    1.447     2.17  12   \n D       2.16 0.181 66    1.802     2.53   2   \n A       3.76 0.181 66    3.399     4.12    3  \n B       3.88 0.181 66    3.514     4.24    3  \n F       4.02 0.181 66    3.656     4.38    3  \n\nConfidence level used: 0.95 \nP value adjustment: tukey method for comparing a family of 6 estimates \nsignificance level used: alpha = 0.05 \nNOTE: If two or more means share the same grouping symbol,\n      then we cannot show them to be different.\n      But we also did not show them to be the same. \n```\n:::\n:::\n\n\nCom a média transformada, são criados 3 grupos, ou seja, a discriminação foi melhor, e com isso a comparação foi melhor.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-70_8b9ab9333a9fc4a10e19e27f7dc01283'}\n\n```{.r .cell-code}\npwpm(m2_medias)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       A      B      C      D      E      F\nA [3.76] 0.9975 <.0001 <.0001 <.0001 0.9145\nB -0.116 [3.88] <.0001 <.0001 <.0001 0.9936\nC  2.516  2.632 [1.24] 0.0081 0.2513 <.0001\nD  1.596  1.712 -0.919 [2.16] 0.7366 <.0001\nE  1.951  2.067 -0.565  0.355 [1.81] <.0001\nF -0.258 -0.142 -2.774 -1.854 -2.209 [4.02]\n\nRow and column labels: spray\nUpper triangle: P values   adjust = \"tukey\"\nDiagonal: [Estimates] (emmean) \nLower triangle: Comparisons (estimate)   earlier vs. later\n```\n:::\n:::\n\n\nAs médias encontram-se na diagonal. Acima estão os valores de P valor para comparação das médias.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-71_21a2cca729e3967752503e60533b261c'}\n\n```{.r .cell-code}\npwpp(m2_medias)\n```\n\n::: {.cell-output-display}\n![](Aula_06_07_files/figure-html/unnamed-chunk-71-1.png){width=672}\n:::\n:::\n\n\n### Alternativa 02 - teste não paramétrico\n\nO teste não paramétrico leva em consideração os valores originais, sem transformação.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-72_6febb3b684989743f9da28ced5de3026'}\n\n```{.r .cell-code}\nkruskal.test(count ~ spray,\n             data = inseticida)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tKruskal-Wallis rank sum test\n\ndata:  count by spray\nKruskal-Wallis chi-squared = 54.691, df = 5, p-value = 1.511e-10\n```\n:::\n:::\n\n\nHipótese nula = as médias são iguais.\n\nRejeita-se a hipótese nula, porque o P é menor que 0,05.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-73_ee96c590828b6b7b354b4bfbc333d965'}\n\n```{.r .cell-code}\nm3 <- kruskal(inseticida$count,\n        inseticida$spray,\n        group = TRUE)\nm3\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$statistics\n     Chisq Df      p.chisq  t.value      MSD\n  54.69134  5 1.510845e-10 1.996564 8.462804\n\n$parameters\n            test p.ajusted           name.t ntr alpha\n  Kruskal-Wallis      none inseticida$spray   6  0.05\n\n$means\n  inseticida.count     rank      std  r Min Max   Q25  Q50   Q75\nA        14.500000 52.16667 4.719399 12   7  23 11.50 14.0 17.75\nB        15.333333 54.83333 4.271115 12   7  21 12.50 16.5 17.50\nC         2.083333 11.45833 1.975225 12   0   7  1.00  1.5  3.00\nD         4.916667 25.58333 2.503028 12   2  12  3.75  5.0  5.00\nE         3.500000 19.33333 1.732051 12   1   6  2.75  3.0  5.00\nF        16.666667 55.62500 6.213378 12   9  26 12.50 15.0 22.50\n\n$comparison\nNULL\n\n$groups\n  inseticida$count groups\nF         55.62500      a\nB         54.83333      a\nA         52.16667      a\nD         25.58333      b\nE         19.33333     bc\nC         11.45833      c\n\nattr(,\"class\")\n[1] \"group\"\n```\n:::\n:::\n\n\nEste comando utiliza o teste Fisher. Utiliza o ranking criado para calcular a estatística de agrupamento.\n\nO teste não paramétrico trouxe o mesmo resultado que o teste paramétrico transformado (extraindo a raiz).\n\n### Alternativa 03 - GLMs\n\nUsa uma estatística mais moderna, não levando em conta se a distribuição é normal. Usa a distribuição de Poisson.\n\nO teste generalizado é mais aceito e estudado por trabalhar os dados originais. É uma forma mais \"elegante\" de trabalhar os dados.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-74_40b90a21082c794c01733b467633c77c'}\n\n```{.r .cell-code}\nm4 <- glm(count ~ spray,\n          family = poisson,\n          data = inseticida)\nm4\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:  glm(formula = count ~ spray, family = poisson, data = inseticida)\n\nCoefficients:\n(Intercept)       sprayB       sprayC       sprayD       sprayE       sprayF  \n    2.67415      0.05588     -1.94018     -1.08152     -1.42139      0.13926  \n\nDegrees of Freedom: 71 Total (i.e. Null);  66 Residual\nNull Deviance:\t    409 \nResidual Deviance: 98.33 \tAIC: 376.6\n```\n:::\n:::\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-75_b84c706eb9b25bb9214417f73640d6fa'}\n\n```{.r .cell-code}\nsummary(m4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = count ~ spray, family = poisson, data = inseticida)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  2.67415    0.07581  35.274  < 2e-16 ***\nsprayB       0.05588    0.10574   0.528    0.597    \nsprayC      -1.94018    0.21389  -9.071  < 2e-16 ***\nsprayD      -1.08152    0.15065  -7.179 7.03e-13 ***\nsprayE      -1.42139    0.17192  -8.268  < 2e-16 ***\nsprayF       0.13926    0.10367   1.343    0.179    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for poisson family taken to be 1)\n\n    Null deviance: 409.041  on 71  degrees of freedom\nResidual deviance:  98.329  on 66  degrees of freedom\nAIC: 376.59\n\nNumber of Fisher Scoring iterations: 5\n```\n:::\n\n```{.r .cell-code}\nAnova(m4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Deviance Table (Type II tests)\n\nResponse: count\n      LR Chisq Df Pr(>Chisq)    \nspray   310.71  5  < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-76_bcd79b75716d61af0460a4f0a02ee521'}\n\n```{.r .cell-code}\nplot(simulateResiduals(m4))\n```\n\n::: {.cell-output-display}\n![](Aula_06_07_files/figure-html/unnamed-chunk-76-1.png){width=672}\n:::\n:::\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-77_07e63f32f35a5ed2fb30bce36c6580f6'}\n\n```{.r .cell-code}\nm4_medias <- emmeans(m4, ~ spray,\n                     type = \"response\")\nm4_medias\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n spray  rate    SE  df asymp.LCL asymp.UCL\n A     14.50 1.099 Inf     12.50     16.82\n B     15.33 1.130 Inf     13.27     17.72\n C      2.08 0.417 Inf      1.41      3.08\n D      4.92 0.640 Inf      3.81      6.35\n E      3.50 0.540 Inf      2.59      4.74\n F     16.67 1.179 Inf     14.51     19.14\n\nConfidence level used: 0.95 \nIntervals are back-transformed from the log scale \n```\n:::\n:::\n\n\nO intervalo indica que 95% das vezes a média se encontra dentro do intervalo.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-78_c17c58e2a71c53b71a90fc110d439d8c'}\n\n```{.r .cell-code}\ncld(m4_medias)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n spray  rate    SE  df asymp.LCL asymp.UCL .group\n C      2.08 0.417 Inf      1.41      3.08  1    \n E      3.50 0.540 Inf      2.59      4.74  12   \n D      4.92 0.640 Inf      3.81      6.35   2   \n A     14.50 1.099 Inf     12.50     16.82    3  \n B     15.33 1.130 Inf     13.27     17.72    3  \n F     16.67 1.179 Inf     14.51     19.14    3  \n\nConfidence level used: 0.95 \nIntervals are back-transformed from the log scale \nP value adjustment: tukey method for comparing a family of 6 estimates \nTests are performed on the log scale \nsignificance level used: alpha = 0.05 \nNOTE: If two or more means share the same grouping symbol,\n      then we cannot show them to be different.\n      But we also did not show them to be the same. \n```\n:::\n:::\n\n\nEste teste também separa em 3 grupos, da mesma forma que os dados transformados. Só que aqui, os dados são originais.\n\n## Transformação Box-Cox\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-79_311126c00a78cbcd710591901c206ff9'}\n\n```{.r .cell-code}\nb <- boxcox(lm(inseticida$count+0.1 ~1))\n```\n\n::: {.cell-output-display}\n![](Aula_06_07_files/figure-html/unnamed-chunk-79-1.png){width=672}\n:::\n:::\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-80_2088bcef195fc3f81f324a04f6155f64'}\n\n```{.r .cell-code}\nlambda <- b$x[which.max(b$y)]\nlambda\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.4242424\n```\n:::\n:::\n\n\nCriando a variável transformada.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-81_13700014586e3a7e2ffb2922ae04045e'}\n\n```{.r .cell-code}\ninseticida$count3 <- (inseticida$count ^ lambda - 1) / lambda\ninseticida$count3\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1]  3.903635  3.024469  6.043993  4.864268  4.864268  4.407118  3.903635\n [8]  6.557185  5.484274  6.043993  4.864268  4.640760  4.161975  5.484274\n[15]  6.219699  4.161975  5.285168  4.864268  5.484274  5.484274  5.863153\n[22]  6.219699  3.024469  4.640760 -2.357143  0.000000  3.024469  0.805831\n[29]  1.399509  0.000000  0.805831  0.000000  1.399509 -2.357143  0.000000\n[36]  1.887150  1.399509  2.308577  4.407118  2.683787  1.887150  1.399509\n[43]  2.308577  2.308577  2.308577  2.308577  0.805831  1.887150  1.399509\n[50]  2.308577  1.399509  2.308577  1.399509  2.683787  0.000000  0.000000\n[57]  1.399509  0.805831  2.683787  1.887150  4.161975  3.629951  5.078760\n[64]  6.390651  5.078760  5.285168  4.640760  3.903635  7.033117  7.033117\n[71]  6.719601  4.640760\n```\n:::\n:::\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-82_dbc8bcd959287ffe805fe29754936392'}\n\n```{.r .cell-code}\nhist(inseticida$count)\n```\n\n::: {.cell-output-display}\n![](Aula_06_07_files/figure-html/unnamed-chunk-82-1.png){width=672}\n:::\n:::\n\n\n### Parte 02 - aula 07\n\nAplicação de Anova fatorial 2x2\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-83_fa381c83cc2ec5dfbef2d314c7406dfb'}\n\n```{.r .cell-code}\nli <- gsheet2tbl(\"https://docs.google.com/spreadsheets/d/1bq2N19DcZdtax2fQW9OHSGMR0X2__Z9T/edit#gid=2023059672\")\nli\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 20 × 8\n   treat         dose   rep  n_sp dis_sp n_seeds inf_seeds severity\n   <chr>        <dbl> <dbl> <dbl>  <dbl>   <dbl>     <dbl>    <dbl>\n 1 Ionic liquid   0.5     1   103     13      25        10   0.126 \n 2 Ionic liquid   0.5     2   125     31      25        12   0.248 \n 3 Ionic liquid   0.5     3   210     80      25        12   0.381 \n 4 Ionic liquid   0.5     4    97     28      25        10   0.289 \n 5 Ionic liquid   0.5     5   180     75      25        11   0.417 \n 6 Ionic liquid   2       2   116      9      25         6   0.0776\n 7 Ionic liquid   2       3   166      7      25         3   0.0422\n 8 Ionic liquid   2       4   157     12      25         1   0.0764\n 9 Ionic liquid   2       5   129      7      25         7   0.0543\n10 Ionic liquid   2       1    84      0      25         1   0     \n11 Tebuconazole   0.5     1   121      0      25         2   0     \n12 Tebuconazole   0.5     2   123      6      25         5   0.0488\n13 Tebuconazole   0.5     3   107      3      25         1   0.0280\n14 Tebuconazole   0.5     4    90      0      25         2   0     \n15 Tebuconazole   0.5     5   142      4      25         1   0.0282\n16 Tebuconazole   2       1   166      3      25         5   0.0181\n17 Tebuconazole   2       2   120      0      25         2   0     \n18 Tebuconazole   2       3   100      4      25         2   0.04  \n19 Tebuconazole   2       4    96      3      25         0   0.0312\n20 Tebuconazole   2       5   170      2      25         4   0.0118\n```\n:::\n:::\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-84_4372559c921cf77c2459b07b7971d5a4'}\n\n```{.r .cell-code}\nsev <- li |> \n  ggplot(aes(dose, severity, color = factor(dose)))+\n  geom_jitter(width = 0.1)+\n  facet_wrap(~treat)+\n  theme_bw()\n  \nsev\n```\n\n::: {.cell-output-display}\n![](Aula_06_07_files/figure-html/unnamed-chunk-84-1.png){width=672}\n:::\n:::\n\n\nO gráfico mostra que a dose 2 do líquido iônico reduziu a severidade da doença semelhantemente às doses de fungicidas aplicados no outro nível de fator (tebuconazol). Para próximos experimentos poderiam ser realizados outros níveis do fator líquido iônico.\n\n### Modelo Fatorial (two-way ANOVA)\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-85_54d8aae26e8ca8e61420cbed28f50fb9'}\n\n```{.r .cell-code}\nmf <- lm(severity ~ treat*factor(dose),\n         data = li)\nmf\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = severity ~ treat * factor(dose), data = li)\n\nCoefficients:\n                    (Intercept)                treatTebuconazole  \n                         0.2921                          -0.2711  \n                  factor(dose)2  treatTebuconazole:factor(dose)2  \n                        -0.2420                           0.2412  \n```\n:::\n\n```{.r .cell-code}\nanova(mf)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Variance Table\n\nResponse: severity\n                   Df   Sum Sq  Mean Sq F value    Pr(>F)    \ntreat               1 0.113232 0.113232  30.358 4.754e-05 ***\nfactor(dose)        1 0.073683 0.073683  19.755 0.0004077 ***\ntreat:factor(dose)  1 0.072739 0.072739  19.502 0.0004326 ***\nResiduals          16 0.059678 0.003730                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\nAparecem mais duas linhas: dose, e interação tratamento:dose.\n\nOcorre uma interação significativa. Devemos estimar as médias de um dentro do outro, ou seja, a combinação dos tratamentos. As médias devem ser estimadas pelas interações significativas, devem ser decompostas para haver comparação.\n\nLetras maiúsculas comparam as colunas, letras minúsculas comparam as linhas.\n\n#### Testando as premissas\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-86_64c58544f0d6abf44d3cffc7628ccb34'}\n\n```{.r .cell-code}\nplot(simulateResiduals(mf))\n```\n\n::: {.cell-output-display}\n![](Aula_06_07_files/figure-html/unnamed-chunk-86-1.png){width=672}\n:::\n:::\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-87_b80ed9c3ddc8a32c8f0ddf6ce861d0ad'}\n\n```{.r .cell-code}\ncheck_normality(mf)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nWarning: Non-normality of residuals detected (p = 0.011).\n```\n:::\n:::\n\n\nEstimar as médias do fungicida para cada dose.\n\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-88_0964152fa725c9f403900be2146fe650'}\n\n```{.r .cell-code}\nmf_medias <- emmeans(mf, ~ treat | dose)\ncld(mf_medias)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ndose = 0.5:\n treat        emmean     SE df lower.CL upper.CL .group\n Tebuconazole 0.0210 0.0273 16 -0.03690   0.0789  1    \n Ionic liquid 0.2921 0.0273 16  0.23420   0.3500   2   \n\ndose = 2.0:\n treat        emmean     SE df lower.CL upper.CL .group\n Tebuconazole 0.0202 0.0273 16 -0.03768   0.0781  1    \n Ionic liquid 0.0501 0.0273 16 -0.00781   0.1080  1    \n\nConfidence level used: 0.95 \nsignificance level used: alpha = 0.05 \nNOTE: If two or more means share the same grouping symbol,\n      then we cannot show them to be different.\n      But we also did not show them to be the same. \n```\n:::\n:::\n\n::: {.cell hash='Aula_06_07_cache/html/unnamed-chunk-89_9b54259e791f5e8fa17bec7451562132'}\n\n```{.r .cell-code}\nmf_medias <- emmeans(mf, ~ dose | treat)\ncld(mf_medias)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ntreat = Ionic liquid:\n dose emmean     SE df lower.CL upper.CL .group\n  2.0 0.0501 0.0273 16 -0.00781   0.1080  1    \n  0.5 0.2921 0.0273 16  0.23420   0.3500   2   \n\ntreat = Tebuconazole:\n dose emmean     SE df lower.CL upper.CL .group\n  2.0 0.0202 0.0273 16 -0.03768   0.0781  1    \n  0.5 0.0210 0.0273 16 -0.03690   0.0789  1    \n\nConfidence level used: 0.95 \nsignificance level used: alpha = 0.05 \nNOTE: If two or more means share the same grouping symbol,\n      then we cannot show them to be different.\n      But we also did not show them to be the same. \n```\n:::\n:::\n\n\nAs duas tabelas acima indicam as letras para difenrenciação das médias.\n\n| Tratamento | 0,5     | 2,0     |\n|------------|---------|---------|\n| LI         | 0,29 Aa | 0,05 Ab |\n| TEB        | 0,02 Ba | 0,02 Aa |\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}