<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Caderno de aulas - Aula_06</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./img02.jpeg" rel="icon" type="image/jpeg">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    <img src="./img02.jpeg" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Caderno de aulas</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-r-básico" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">R básico</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-r-básico">    
        <li>
    <a class="dropdown-item" href="./Introducao.html" rel="" target="">
 <span class="dropdown-text">Introdução ao RStudio</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./Aula_01.html" rel="" target="">
 <span class="dropdown-text">Comandos básicos para começar no R</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-importação-de-arquivos" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Importação de arquivos</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-importação-de-arquivos">    
        <li>
    <a class="dropdown-item" href="./aula_02.html" rel="" target="">
 <span class="dropdown-text">Planilhas Excel e Docs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./aula_03.html" rel="" target="">
 <span class="dropdown-text">Importação de arquivos Web</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-gráficos-no-rstudio" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Gráficos no RStudio</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-gráficos-no-rstudio">    
        <li>
    <a class="dropdown-item" href="./aula_04.html" rel="" target="">
 <span class="dropdown-text">Gráficos em <strong>ggplot</strong> parte 01</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./Aula_05.html" rel="" target="">
 <span class="dropdown-text">Gráficos em <strong>ggplot</strong> parte 02</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-estatística-no-rstudio" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Estatística no RStudio</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-estatística-no-rstudio">    
        <li>
    <a class="dropdown-item" href="./Aula_06_07.html" rel="" target="">
 <span class="dropdown-text">Estatística descritiva e inferencial - Testes</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./Aula_08.html" rel="" target="">
 <span class="dropdown-text">Análises estatísticas - Regressão</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./Aula_09.html" rel="" target="">
 <span class="dropdown-text">Análises estatísticas - LM e GLM</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./Aula_10.html" rel="" target="">
 <span class="dropdown-text">Análises estatísticas - Correlação</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-mapas-no-rstudio" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Mapas no Rstudio</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-mapas-no-rstudio">    
        <li>
    <a class="dropdown-item" href="./aula_11.html" rel="" target="">
 <span class="dropdown-text">Criando Mapas</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#aula-06---17042024" id="toc-aula-06---17042024" class="nav-link active" data-scroll-target="#aula-06---17042024">AULA 06 - 17/04/2024</a>
  <ul class="collapse">
  <li><a href="#estatística-descritiva-e-estatística-inferencial" id="toc-estatística-descritiva-e-estatística-inferencial" class="nav-link" data-scroll-target="#estatística-descritiva-e-estatística-inferencial">Estatística Descritiva e Estatística Inferencial</a></li>
  <li><a href="#pacotes" id="toc-pacotes" class="nav-link" data-scroll-target="#pacotes">Pacotes</a>
  <ul class="collapse">
  <li><a href="#estatística-descritiva" id="toc-estatística-descritiva" class="nav-link" data-scroll-target="#estatística-descritiva">Estatística Descritiva</a></li>
  <li><a href="#carregando-o-pacote-de-dados" id="toc-carregando-o-pacote-de-dados" class="nav-link" data-scroll-target="#carregando-o-pacote-de-dados">Carregando o pacote de dados</a></li>
  <li><a href="#tratamentos-independentes" id="toc-tratamentos-independentes" class="nav-link" data-scroll-target="#tratamentos-independentes">Tratamentos independentes</a></li>
  </ul></li>
  <li><a href="#teste-estatístico" id="toc-teste-estatístico" class="nav-link" data-scroll-target="#teste-estatístico">Teste estatístico</a>
  <ul class="collapse">
  <li><a href="#teste-t-student" id="toc-teste-t-student" class="nav-link" data-scroll-target="#teste-t-student">Teste “T” student</a></li>
  <li><a href="#realizando-o-teste-t-student" id="toc-realizando-o-teste-t-student" class="nav-link" data-scroll-target="#realizando-o-teste-t-student">Realizando o teste T-student</a></li>
  </ul></li>
  <li><a href="#teste-de-normalidade" id="toc-teste-de-normalidade" class="nav-link" data-scroll-target="#teste-de-normalidade">Teste de normalidade</a>
  <ul class="collapse">
  <li><a href="#shapiro-wilk" id="toc-shapiro-wilk" class="nav-link" data-scroll-target="#shapiro-wilk">Shapiro wilk</a></li>
  <li><a href="#report" id="toc-report" class="nav-link" data-scroll-target="#report">Report</a></li>
  </ul></li>
  <li><a href="#dois-grupos-dependentes" id="toc-dois-grupos-dependentes" class="nav-link" data-scroll-target="#dois-grupos-dependentes">Dois grupos dependentes</a>
  <ul class="collapse">
  <li><a href="#teste-não-paramétrico" id="toc-teste-não-paramétrico" class="nav-link" data-scroll-target="#teste-não-paramétrico">Teste não paramétrico</a></li>
  </ul></li>
  <li><a href="#teste-de-comparação-de-médias" id="toc-teste-de-comparação-de-médias" class="nav-link" data-scroll-target="#teste-de-comparação-de-médias">Teste de comparação de médias</a></li>
  </ul></li>
  <li><a href="#aula-07---24042024" id="toc-aula-07---24042024" class="nav-link" data-scroll-target="#aula-07---24042024">AULA 07 - 24/04/2024</a>
  <ul class="collapse">
  <li><a href="#barlett-test" id="toc-barlett-test" class="nav-link" data-scroll-target="#barlett-test">Barlett Test</a></li>
  <li><a href="#alternativa-01---extração-da-raiz-quadrada" id="toc-alternativa-01---extração-da-raiz-quadrada" class="nav-link" data-scroll-target="#alternativa-01---extração-da-raiz-quadrada">Alternativa 01 - Extração da Raiz quadrada</a></li>
  <li><a href="#alternativa-02---teste-não-paramétrico" id="toc-alternativa-02---teste-não-paramétrico" class="nav-link" data-scroll-target="#alternativa-02---teste-não-paramétrico">Alternativa 02 - teste não paramétrico</a></li>
  <li><a href="#alternativa-03---glms" id="toc-alternativa-03---glms" class="nav-link" data-scroll-target="#alternativa-03---glms">Alternativa 03 - GLMs</a></li>
  <li><a href="#transformação-box-cox" id="toc-transformação-box-cox" class="nav-link" data-scroll-target="#transformação-box-cox">Transformação Box-Cox</a>
  <ul class="collapse">
  <li><a href="#parte-02---aula-07" id="toc-parte-02---aula-07" class="nav-link" data-scroll-target="#parte-02---aula-07">Parte 02 - aula 07</a></li>
  <li><a href="#modelo-fatorial-two-way-anova" id="toc-modelo-fatorial-two-way-anova" class="nav-link" data-scroll-target="#modelo-fatorial-two-way-anova">Modelo Fatorial (two-way ANOVA)</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Aula_06</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="aula-06---17042024" class="level1">
<h1>AULA 06 - 17/04/2024</h1>
<section id="estatística-descritiva-e-estatística-inferencial" class="level2">
<h2 class="anchored" data-anchor-id="estatística-descritiva-e-estatística-inferencial">Estatística Descritiva e Estatística Inferencial</h2>
</section>
<section id="pacotes" class="level2">
<h2 class="anchored" data-anchor-id="pacotes">Pacotes</h2>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-1_689ee5bab8e912df8a2cc5f27082feb3">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gsheet)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(report)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(multcomp)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(multcompView)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DHARMa)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(performance)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(agricolae)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co">#library(MASS)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="estatística-descritiva" class="level3">
<h3 class="anchored" data-anchor-id="estatística-descritiva">Estatística Descritiva</h3>
<p>A estatística descritiva pode ser resumida na qual organiza a coleta, a apuração e a descrição dos dados para amostras, sem almejar conclusões categóricas para as populações nas quais essas amostras se originaram.</p>
</section>
<section id="carregando-o-pacote-de-dados" class="level3">
<h3 class="anchored" data-anchor-id="carregando-o-pacote-de-dados">Carregando o pacote de dados</h3>
<p>Pacote de dados disponíveis em planilha no google drive.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-2_0d85a783d37e3a49f6b00f56619b9051">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>mg <span class="ot">&lt;-</span> <span class="fu">gsheet2tbl</span>(<span class="st">"https://docs.google.com/spreadsheets/d/1bq2N19DcZdtax2fQW9OHSGMR0X2__Z9T/edit#gid=983033137"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_bw</span>())</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>mg</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 3
   trat      rep  comp
   &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt;
 1 Mg2         1   9  
 2 Mg2         2  12.5
 3 Mg2         3  10  
 4 Mg2         4   8  
 5 Mg2         5  13.2
 6 Mg2         6  11  
 7 Mg2         7  10.8
 8 Mg2         8   9.5
 9 Mg2         9  10.8
10 Mg2        10  10.4
11 control     1  13.7
12 control     2  15.9
13 control     3  15.7
14 control     4  14.2
15 control     5  15.9
16 control     6  16.5
17 control     7  18  
18 control     8  14.4
19 control     9  16.4
20 control    10  16  </code></pre>
</div>
</div>
</section>
<section id="tratamentos-independentes" class="level3">
<h3 class="anchored" data-anchor-id="tratamentos-independentes">Tratamentos independentes</h3>
<p>Um pesquisador conduziu um experimento com o objetivo de avaliar o efeito de um micronutriente, o magnésio (Mg), adicionado na solução do solo cultivado com plantas de arroz, no manejo de uma doença fúngica. O experimento foi conduzido em delineamento inteiramente casualizado com 10 repetições, sendo cada repetição um vaso de planta. Um dos tratamentos é o chamado controle, ou testemunha, sem o suplemento mineral. O segundo é aquele com o suplemento do Mg na dose de 2 mM. Em cada uma das repetições foi obtido um valor médio do comprimento de lesões em um determinado tempo após a inoculação.</p>
<p>Os gráficos a seguir mostram que o incremento de magnésio reduz a severidade da doença, ou seja, induz a resistência. Visualmente indica que existe um efeito. Mas, uma hipótese científica deve ser testada.</p>
<p>Hipótese: o incremento de magnésio aumenta a resistência a doença;</p>
<p>Hipótese estatística: não existem diferenças entre os tratamentos.</p>
<p>Usa-se o teste “T” para número de amostras igual ou inferior a 30. Usa-se o teste “T” para grupos independentes.</p>
<p>Premissas: Teste de normalidade e variâncias homogêneas.</p>
<p>Podemos assumir estas premissas através de uma análise exploratória, através da simetria do boxplot. Assume-se visualmente que as variâncias são iguais e que existe uma normalidade, mas, isso pode ser testado. Devemos primeiramente verificar as premissas.</p>
<p>Se a distribuição não for normal, devemos realizar o teste não paramétrico, como o shapiro-wilk.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-3_2521535de8d47b21e86f68c0c5eb4927">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>mg <span class="sc">|&gt;</span> </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(trat, comp))<span class="sc">+</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Aula_06_07_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="teste-estatístico" class="level2">
<h2 class="anchored" data-anchor-id="teste-estatístico">Teste estatístico</h2>
<section id="teste-t-student" class="level3">
<h3 class="anchored" data-anchor-id="teste-t-student">Teste “T” student</h3>
<p>O teste t compara duas médias e mostra se as diferenças entre essas médias são significativas. A necessidade de determinar se duas médias de amostras são diferentes entre si é uma situação extremamente frequente em pesquisas científicas. Como todo teste estatístico, o teste t também tem como produto a medida do p valor. Ou seja, calculamos a probabilidade da diferença encontrada (entre as médias) terem sido por acaso.</p>
<p>É ideal que tenhamos os vetores separados em duas colunas, em formato largo. Para realizar essa conversão, faremos o seguite comando, atribuindo ao mg2.</p>
<p>Precisamos de uma coluna para cada tratamento.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-4_f8561ca063429ddb6cc163bddcc0062f">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>?t.test</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>mg2 <span class="ot">&lt;-</span> mg <span class="sc">|&gt;</span> </span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> trat,</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">values_from =</span> comp)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>mg2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 3
     rep   Mg2 control
   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
 1     1   9      13.7
 2     2  12.5    15.9
 3     3  10      15.7
 4     4   8      14.2
 5     5  13.2    15.9
 6     6  11      16.5
 7     7  10.8    18  
 8     8   9.5    14.4
 9     9  10.8    16.4
10    10  10.4    16  </code></pre>
</div>
</div>
</section>
<section id="realizando-o-teste-t-student" class="level3">
<h3 class="anchored" data-anchor-id="realizando-o-teste-t-student">Realizando o teste T-student</h3>
<p>A primeira média (X) é referente ao tratamento mg2, que foi incluído primeiro na fórmula.</p>
<p>Encontrou-se uma diferença, mesmo em uma probabilidade muito pequena.</p>
<p>Até agora, assume-se que o teste T é confiável, existe uma diferença estatística.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-5_bb110ab877aa388a4c9468ac7e166f91">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>teste1 <span class="ot">&lt;-</span> <span class="fu">t.test</span>(mg2<span class="sc">$</span>Mg2, mg2<span class="sc">$</span>control)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  teste1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  mg2$Mg2 and mg2$control
t = -8.1549, df = 17.354, p-value = 2.423e-07
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -6.490393 -3.825607
sample estimates:
mean of x mean of y 
   10.520    15.678 </code></pre>
</div>
</div>
<p>Vamos obter estatísticas que descrevem o conjunto, seja a tendência central ou a dispersão dos dados. No caso, será a média, variância, desvio padrão, erro padrão e intervalo de confiança - esse último para inferência visual.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-6_dea5b0d6e44b42de139aea8e174198fb">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>dat2 <span class="ot">&lt;-</span> mg <span class="sc">|&gt;</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(trat) <span class="sc">|&gt;</span> </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_comp =</span> <span class="fu">mean</span>(comp),</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_comp =</span> <span class="fu">sd</span>(comp),</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">var_comp =</span> <span class="fu">var</span>(comp),</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">se_comp =</span> sd_comp <span class="sc">/</span> <span class="fu">sqrt</span>(n <span class="sc">-</span> <span class="dv">1</span>),</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">ci =</span> se_comp <span class="sc">*</span> <span class="fu">qt</span>(<span class="fl">0.025</span>, <span class="at">df =</span> <span class="dv">9</span>))</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>dat2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  trat    mean_comp sd_comp var_comp     n se_comp     ci
  &lt;chr&gt;       &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt;  &lt;dbl&gt;
1 Mg2          10.5    1.54     2.39    10   0.515 -1.16 
2 control      15.7    1.27     1.61    10   0.424 -0.958</code></pre>
</div>
</div>
<p>Já podemos visualizar os dados com as estatísticas calculadas. Abaixo, as barras verticais representam o intervalo de confiança 95%.</p>
</section>
</section>
<section id="teste-de-normalidade" class="level2">
<h2 class="anchored" data-anchor-id="teste-de-normalidade">Teste de normalidade</h2>
<section id="shapiro-wilk" class="level3">
<h3 class="anchored" data-anchor-id="shapiro-wilk">Shapiro wilk</h3>
<p>O Teste de Shapiro-Wilk tem como objetivo avaliar se uma distribuição é semelhante a uma&nbsp;<a href="https://www.blog.psicometriaonline.com.br/blog/distribuicao-normal/">distribuição normal</a>. A distribuição normal&nbsp;também pode ser chamada de gaussiana e sua forma assemelha-se a de um sino. Esse tipo de distribuição é muito importante, por ser frequentemente usada para modelar fenômenos naturais.</p>
<p>Se o valor foi acima de 0,05, aceito que a distribuição é normal. Menor que 0,05 rejeita-se a hipótese nula, de que a distribuição não é normal.</p>
<p>Neste caso, assume-se que a distribuição é normal.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-7_f25dee598751350bbdf8faedbeaa1b4e">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(mg2<span class="sc">$</span>control)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  mg2$control
W = 0.93886, p-value = 0.5404</code></pre>
</div>
</div>
<p>Histograma para observação de normalidade.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-8_852aa9918d6b44324423f9513dc3b509">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(mg2<span class="sc">$</span>control)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Aula_06_07_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-9_83d99c83437783c9909b40df1994ed54">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(mg2<span class="sc">$</span>Mg2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Aula_06_07_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-10_fa2db374fbec9bbbcff8c262d2a87665">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(mg2<span class="sc">$</span>Mg2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  mg2$Mg2
W = 0.97269, p-value = 0.9146</code></pre>
</div>
</div>
<p>Para comparar variâncias.</p>
<p>Posso assumir como variáveis homogêneas, valor de P mostrou-se alto. Podemos continuar normalmente com o teste T.</p>
<p>Verificaram-se as premissas de normalidade e de variância.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-11_d19af0daa823a51eac30a451b7eb8f53">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var.test</span>(mg2<span class="sc">$</span>control, mg2<span class="sc">$</span>Mg2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    F test to compare two variances

data:  mg2$control and mg2$Mg2
F = 0.67654, num df = 9, denom df = 9, p-value = 0.5698
alternative hypothesis: true ratio of variances is not equal to 1
95 percent confidence interval:
 0.1680428 2.7237436
sample estimates:
ratio of variances 
         0.6765394 </code></pre>
</div>
</div>
<p>Assumindo a variância como verdadeira, informando-a como homogênea.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-12_81c938d7cb8d39b6b9ff8d5710b531cc">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var.test</span>(mg2<span class="sc">$</span>control, mg2<span class="sc">$</span>Mg2, </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    F test to compare two variances

data:  mg2$control and mg2$Mg2
F = 0.67654, num df = 9, denom df = 9, p-value = 0.5698
alternative hypothesis: true ratio of variances is not equal to 1
95 percent confidence interval:
 0.1680428 2.7237436
sample estimates:
ratio of variances 
         0.6765394 </code></pre>
</div>
</div>
<p>Quanto mais próximos os pontos estão da linha, indicam maior normalidade das variâncias. Isso quer dizer que as resultados dentro de cada grupo foram semelhantes.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-13_04746e39bd82eaaeea6c15115db4e7f4">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(mg2<span class="sc">$</span>control)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(mg2<span class="sc">$</span>control)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Aula_06_07_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="report" class="level3">
<h3 class="anchored" data-anchor-id="report">Report</h3>
<p>Monta um texto base que pode ser usado no artigo.</p>
<p>“Effect sizes were labelled following Cohen’s (1988) recommendations. The Welch Two Sample t-test testing the difference between mg2$Mg2 and mg2$control (mean of x = 10.52, mean of y = 15.68) suggests that the effect is negative, statistically significant, and large (difference = -5.16, 95% CI [-6.49, -3.83], t(17.35) = -8.15, p &lt; .001.”</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-14_56bc7ee529f9841bac2bb08e1cdbc882">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">report</span>(teste1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Effect sizes were labelled following Cohen's (1988) recommendations.

The Welch Two Sample t-test testing the difference between mg2$Mg2 and
mg2$control (mean of x = 10.52, mean of y = 15.68) suggests that the effect is
negative, statistically significant, and large (difference = -5.16, 95% CI
[-6.49, -3.83], t(17.35) = -8.15, p &lt; .001; Cohen's d = -3.65, 95% CI [-5.12,
-2.14])</code></pre>
</div>
</div>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-15_2dc975a5c205ae9efd665489b30f97c5">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(mg2<span class="sc">$</span>control, mg2<span class="sc">$</span>Mg2, </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">paired =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum test with continuity correction

data:  mg2$control and mg2$Mg2
W = 100, p-value = 0.0001817
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
</section>
</section>
<section id="dois-grupos-dependentes" class="level2">
<h2 class="anchored" data-anchor-id="dois-grupos-dependentes">Dois grupos dependentes</h2>
<p>Ocorre uma dependência do avaliador, pois ocorre a avaliação com e sem a escala diagramática, ou seja, existe dependência.</p>
<p>Como são dois grupos, usa-se o teste T, mas devemos indicar a dependência. Uso de um teste pareado, diferente do exemplo anterior.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-16_78c94ef2adee376b2dbc59c4f0dfdbd7">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>escala <span class="ot">&lt;-</span> <span class="fu">gsheet2tbl</span>(<span class="st">"https://docs.google.com/spreadsheets/d/1aID5Dh6PlBVCKzU1j7k-WA6zuWQWE2NhtWEgdJtt5iA/edit#gid=1139290215"</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>escala</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 7
   assessment rater acuracia precisao vies_geral vies_sistematico vies_constante
   &lt;chr&gt;      &lt;chr&gt;    &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;            &lt;dbl&gt;          &lt;dbl&gt;
 1 Unaided    A         0.81     0.83       0.98             1.19           0.11
 2 Unaided    B         0.72     0.73       0.99             0.92          -0.11
 3 Unaided    C         0.56     0.71       0.78             1.16           0.73
 4 Unaided    D         0.82     0.82       1                0.95          -0.01
 5 Unaided    E         0.75     0.75       0.99             1.1            0.07
 6 Unaided    F         0.69     0.75       0.92             0.8            0.34
 7 Unaided    G         0.81     0.82       0.98             1.16           0.13
 8 Unaided    H         0.78     0.87       0.9              1.07          -0.47
 9 Unaided    I         0.78     0.79       0.99             1.14           0.09
10 Unaided    J         0.62     0.83       0.74             0.65          -0.72
11 Aided1     A         0.91     0.95       0.96             0.89          -0.28
12 Aided1     B         0.91     0.96       0.95             0.89          -0.3 
13 Aided1     C         0.91     0.96       0.95             1.28           0.21
14 Aided1     D         0.96     0.97       0.99             1.14           0.09
15 Aided1     E         0.96     0.96       1                1             -0.1 
16 Aided1     F         0.9      0.97       0.93             0.86          -0.36
17 Aided1     G         0.85     0.95       0.89             0.83          -0.45
18 Aided1     H         0.88     0.97       0.9              1.29           0.38
19 Aided1     I         0.95     0.96       0.99             1.14           0.07
20 Aided1     J         0.94     0.96       0.99             0.91          -0.13</code></pre>
</div>
</div>
<p>Mostrando a acurácia com e sem o auxílio da escala avaliadora.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-17_271c767f0fcb76e5027cdcdc0f7af9c9">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>escala <span class="sc">|&gt;</span> </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(assessment, acuracia))<span class="sc">+</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Aula_06_07_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="teste-t-para-a-acurácia." class="level4">
<h4 class="anchored" data-anchor-id="teste-t-para-a-acurácia.">Teste T para a acurácia.</h4>
<p>Primeiro passar do formato longo para o formato largo, selecionando na escala 2 apenas os valores de interesse.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-18_d168cafa75728127c734a9b8e4f2a4c2">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>escala2 <span class="ot">&lt;-</span> escala <span class="sc">|&gt;</span> </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(assessment, rater,acuracia) <span class="sc">|&gt;</span> </span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> assessment,</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">values_from =</span> acuracia)</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>escala2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 3
   rater Unaided Aided1
   &lt;chr&gt;   &lt;dbl&gt;  &lt;dbl&gt;
 1 A        0.81   0.91
 2 B        0.72   0.91
 3 C        0.56   0.91
 4 D        0.82   0.96
 5 E        0.75   0.96
 6 F        0.69   0.9 
 7 G        0.81   0.85
 8 H        0.78   0.88
 9 I        0.78   0.95
10 J        0.62   0.94</code></pre>
</div>
</div>
</section>
<section id="teste-shapiro-wilk" class="level4">
<h4 class="anchored" data-anchor-id="teste-shapiro-wilk">Teste shapiro wilk</h4>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-19_59d2bcf2810a283a5ff6655b2b5f4c32">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(escala2<span class="sc">$</span>Unaided)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  escala2$Unaided
W = 0.87881, p-value = 0.1265</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(escala2<span class="sc">$</span>Aided1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  escala2$Aided1
W = 0.92852, p-value = 0.4335</code></pre>
</div>
</div>
<p>Teste de variância.</p>
<p>Rejeita-se H0 por p valor ser menor que 0,05.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-20_89c5d214535fe588efea7651c1efa5de">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var.test</span>(escala2<span class="sc">$</span>Unaided, escala2<span class="sc">$</span>Aided1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    F test to compare two variances

data:  escala2$Unaided and escala2$Aided1
F = 5.9294, num df = 9, denom df = 9, p-value = 0.0141
alternative hypothesis: true ratio of variances is not equal to 1
95 percent confidence interval:
  1.472772 23.871614
sample estimates:
ratio of variances 
          5.929371 </code></pre>
</div>
</div>
<p>O teste pareado dá a diferença entre os dados diferentes. O teste T foi usado porque a distribuição é normal.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-21_8b7f815d4ffd8fb31d76e268bf702fee">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(escala2<span class="sc">$</span>Aided1, escala2<span class="sc">$</span>Unaided,</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">paired =</span> <span class="cn">TRUE</span>,</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">var.equal =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  escala2$Aided1 and escala2$Unaided
t = 5.9755, df = 9, p-value = 0.0002087
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 0.1137215 0.2522785
sample estimates:
mean difference 
          0.183 </code></pre>
</div>
</div>
</section>
<section id="teste-não-paramétrico" class="level3">
<h3 class="anchored" data-anchor-id="teste-não-paramétrico">Teste não paramétrico</h3>
<p>Valores da tabela foram alterados para obtermos um novo boxplot.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-22_a1dc762e6a26f2b4e88774d260c8ec09">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>escala <span class="ot">&lt;-</span> <span class="fu">gsheet2tbl</span>(<span class="st">"https://docs.google.com/spreadsheets/d/1bq2N19DcZdtax2fQW9OHSGMR0X2__Z9T/edit#gid=1729131173"</span>)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>escala</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 7
   assessment rater acuracia precisao vies_geral vies_sistematico vies_constante
   &lt;chr&gt;      &lt;chr&gt;    &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;            &lt;dbl&gt;          &lt;dbl&gt;
 1 Unaided    A         0.81     0.83       0.98             1.19           0.11
 2 Unaided    B         0.72     0.73       0.99             0.92          -0.11
 3 Unaided    C         0.4      0.71       0.78             1.16           0.73
 4 Unaided    D         0.82     0.82       1                0.95          -0.01
 5 Unaided    E         0.75     0.75       0.99             1.1            0.07
 6 Unaided    F         0.45     0.75       0.92             0.8            0.34
 7 Unaided    G         0.81     0.82       0.98             1.16           0.13
 8 Unaided    H         0.78     0.87       0.9              1.07          -0.47
 9 Unaided    I         0.78     0.79       0.99             1.14           0.09
10 Unaided    J         0.5      0.83       0.74             0.65          -0.72
11 Aided1     A         0.91     0.95       0.96             0.89          -0.28
12 Aided1     B         0.91     0.96       0.95             0.89          -0.3 
13 Aided1     C         0.91     0.96       0.95             1.28           0.21
14 Aided1     D         0.96     0.97       0.99             1.14           0.09
15 Aided1     E         0.96     0.96       1                1             -0.1 
16 Aided1     F         0.9      0.97       0.93             0.86          -0.36
17 Aided1     G         0.85     0.95       0.89             0.83          -0.45
18 Aided1     H         0.88     0.97       0.9              1.29           0.38
19 Aided1     I         0.95     0.96       0.99             1.14           0.07
20 Aided1     J         0.94     0.96       0.99             0.91          -0.13</code></pre>
</div>
</div>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-23_f742fb50ca6a3f36fd0f43b7ffdad55c">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>escala <span class="sc">|&gt;</span> </span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(assessment, acuracia))<span class="sc">+</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Aula_06_07_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="teste-wilcox" class="level4">
<h4 class="anchored" data-anchor-id="teste-wilcox">Teste wilcox</h4>
<p>Conclui com base no valor de P. Rejeita-se a hipótese nula, pois os valores são diferentes. Ele corrobora com o teste T.</p>
<p>Quando os dados são pareados, usamos “paired = TRUE”, quando os não são pareados, usamos “paired = FALSE”.</p>
<p>Se as variâncias são heterogêneas, assumimos que “var.equal = FALSE”.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-24_436d047bc0811a28836e6ccda3261f9d">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(escala2<span class="sc">$</span>Aided1,</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>            escala2<span class="sc">$</span>Unaided,</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon signed rank test with continuity correction

data:  escala2$Aided1 and escala2$Unaided
V = 55, p-value = 0.005889
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<p>Teste shapiro wilk para observar normalidade.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-25_e838d8ef04ac218f0bd3549c0c1e4ce3">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(escala2<span class="sc">$</span>Unaided)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  escala2$Unaided
W = 0.87881, p-value = 0.1265</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(escala2<span class="sc">$</span>Aided1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  escala2$Aided1
W = 0.92852, p-value = 0.4335</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="teste-de-comparação-de-médias" class="level2">
<h2 class="anchored" data-anchor-id="teste-de-comparação-de-médias">Teste de comparação de médias</h2>
<p>Estudando o conjunto de dados “micelial”</p>
<p>H0 = Pelo menos uma das médias é diferente das demais.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-26_da7cf6a280d80b22de1ab30d566bab5d">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>micelial <span class="ot">&lt;-</span> <span class="fu">gsheet2tbl</span>(<span class="st">"https://docs.google.com/spreadsheets/d/1bq2N19DcZdtax2fQW9OHSGMR0X2__Z9T/edit#gid=959387827"</span>)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>micelial</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 30 × 3
   especie   rep   tcm
   &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt;
 1 Fasi        1  1.5 
 2 Fasi        2  1.59
 3 Fasi        3  1.52
 4 Fasi        4  1.52
 5 Fasi        5  1.6 
 6 Fasi        6  1.7 
 7 Faus        1  1.52
 8 Faus        2  1.25
 9 Faus        3  1.27
10 Faus        4  1.3 
# ℹ 20 more rows</code></pre>
</div>
</div>
<p>Gráfico jitter para explorar melhor o conjunto de dados.</p>
<p>O que a ANOVA vai testar? Se existe pelo menos uma média que é diferente das outras médias. Ele testa no grupo e entre cada grupo.</p>
<p>A ANOVA vai comparar as médias de 3 ou mais grupos.</p>
<p>Com o gráfico a seguir, não é possível observar visualmente se há ou não diferença entre as médias das espécies. A distribuição não é homogênea.</p>
<p>A variabilidade dentro de cada grupo é grande.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-27_a858baf66e7a5a48e55110a35ad1d3a2">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>micelial <span class="sc">|&gt;</span> </span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(especie, tcm))<span class="sc">+</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.05</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Aula_06_07_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Teste de ANOVA as cegas, sem testar premissas. Através do “aov”.</p>
<p>Se as médias não diferem, não faz mais sentido continuar o teste de comparação de médias.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-28_145464c465848bc6cda998ae4766935b">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>anova1 <span class="ot">&lt;-</span> <span class="fu">aov</span>(tcm <span class="sc">~</span> especie, <span class="at">data =</span> micelial)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(anova1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: tcm
          Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
especie    4 1.46958 0.36739  19.629 2.028e-07 ***
Residuals 25 0.46792 0.01872                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Teste de ANOVA as cegas, sem testar premissas. Através do “lm”. Adicionando o “-1” após a espécie, eu encontro diretamente as médias.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-29_f1588e0cfe663de67a7aa191b1f6adc9">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(tcm <span class="sc">~</span> especie <span class="sc">-</span><span class="dv">1</span>, <span class="at">data =</span> micelial)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: tcm
          Df Sum Sq Mean Sq F value    Pr(&gt;F)    
especie    5 51.677 10.3354   552.2 &lt; 2.2e-16 ***
Residuals 25  0.468  0.0187                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Não existe diferença entre os resultados dos comandos “aov” e “lm”. Dar preferência ao “lm”.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-30_08d9f620f029563a703c0beb6aad7018">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = tcm ~ especie - 1, data = micelial)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.23667 -0.09667  0.01583  0.08833  0.28333 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
especieFasi  1.57167    0.05585   28.14  &lt; 2e-16 ***
especieFaus  1.23667    0.05585   22.14  &lt; 2e-16 ***
especieFcor  1.32167    0.05585   23.66  &lt; 2e-16 ***
especieFgra  0.91167    0.05585   16.32 7.66e-15 ***
especieFmer  1.42667    0.05585   25.54  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1368 on 25 degrees of freedom
Multiple R-squared:  0.991, Adjusted R-squared:  0.9892 
F-statistic: 552.2 on 5 and 25 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Removendo um pouco das variabilidades do conjunto, obtemos a tabela a seguir.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-31_ba4e8044adc9b2d0136c69054956a0e2">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>micelial1 <span class="ot">&lt;-</span> <span class="fu">gsheet2tbl</span>(<span class="st">"https://docs.google.com/spreadsheets/d/1bq2N19DcZdtax2fQW9OHSGMR0X2__Z9T/edit#gid=959387827"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-32_9da1197cf48d77596491eaee49ac8cfe">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>micelial1 <span class="sc">|&gt;</span> </span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(especie, tcm))<span class="sc">+</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.05</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Aula_06_07_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Agora, parece haver alguma diferença entre as médias. Rodaremos os testes.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-33_861e85f8afd2109b63464ff3e7835d71">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(tcm <span class="sc">~</span> especie <span class="sc">-</span><span class="dv">1</span>, <span class="at">data =</span> micelial1)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: tcm
          Df Sum Sq Mean Sq F value    Pr(&gt;F)    
especie    5 51.677 10.3354   552.2 &lt; 2.2e-16 ***
Residuals 25  0.468  0.0187                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-34_e86ae7df3d00912ec16bdad7534400b5">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = tcm ~ especie - 1, data = micelial1)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.23667 -0.09667  0.01583  0.08833  0.28333 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
especieFasi  1.57167    0.05585   28.14  &lt; 2e-16 ***
especieFaus  1.23667    0.05585   22.14  &lt; 2e-16 ***
especieFcor  1.32167    0.05585   23.66  &lt; 2e-16 ***
especieFgra  0.91167    0.05585   16.32 7.66e-15 ***
especieFmer  1.42667    0.05585   25.54  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1368 on 25 degrees of freedom
Multiple R-squared:  0.991, Adjusted R-squared:  0.9892 
F-statistic: 552.2 on 5 and 25 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>O Emmeans define as médias diretamente.</p>
<p>Definindo um teste estatístico para comparação do crescimento.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-35_bebf60fda6ffbab9bba10239df09f49f">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>medias1 <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(m1, <span class="sc">~</span> especie)</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>medias1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> especie emmean     SE df lower.CL upper.CL
 Fasi     1.572 0.0559 25    1.457     1.69
 Faus     1.237 0.0559 25    1.122     1.35
 Fcor     1.322 0.0559 25    1.207     1.44
 Fgra     0.912 0.0559 25    0.797     1.03
 Fmer     1.427 0.0559 25    1.312     1.54

Confidence level used: 0.95 </code></pre>
</div>
</div>
<p>Para adicionar as letras, ou números correspondentes que indicam a diferença, usar o pacote multcomp e multcompview.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-36_99504759de1432cb0d41dec79bd7b36e">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cld</span>(medias1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> especie emmean     SE df lower.CL upper.CL .group
 Fgra     0.912 0.0559 25    0.797     1.03  1    
 Faus     1.237 0.0559 25    1.122     1.35   2   
 Fcor     1.322 0.0559 25    1.207     1.44   2   
 Fmer     1.427 0.0559 25    1.312     1.54   23  
 Fasi     1.572 0.0559 25    1.457     1.69    3  

Confidence level used: 0.95 
P value adjustment: tukey method for comparing a family of 5 estimates 
significance level used: alpha = 0.05 
NOTE: If two or more means share the same grouping symbol,
      then we cannot show them to be different.
      But we also did not show them to be the same. </code></pre>
</div>
</div>
<p>Como saber se o modelo é confiável ou se preciso realizar conversões.</p>
<p>Realizando a análise de normalidade dos resíduos.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-37_772e43dce4f4c55fbd2d39d515df6522">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(m1<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Aula_06_07_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>O teste de shapiro executado indica normalidade dos resíduos. P valor = 0,8782. Não rejeita a hipótese.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-38_fbdb9b7c46e36e3d95f0a269f10d00fe">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(m1<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  m1$residuals
W = 0.9821, p-value = 0.8782</code></pre>
</div>
</div>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-39_b714e9b270f5800a5c45e98b92507eda">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bartlett.test</span>(tcm <span class="sc">~</span> especie, <span class="at">data =</span> micelial1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Bartlett test of homogeneity of variances

data:  tcm by especie
Bartlett's K-squared = 4.4367, df = 4, p-value = 0.3501</code></pre>
</div>
</div>
<p>Plot de diagnóstico dos resíduos.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-40_7c9bcb918ed332b384a18d9ecdfc41ed">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">simulateResiduals</span>(m1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Aula_06_07_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Possibilidade para conferir as premissas.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-41_d2ccc7ed4f37e5cc90273a5d79305d16">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_normality</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: residuals appear as normally distributed (p = 0.878).</code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_heteroscedasticity</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: Error variance appears to be homoscedastic (p = 0.880).</code></pre>
</div>
</div>
<p>Análise dos resíduos.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-42_0b6800f8251f44dbd23f83aaf10fe1c7">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_model</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Aula_06_07_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="aula-07---24042024" class="level1">
<h1>AULA 07 - 24/04/2024</h1>
<p>Continuação da aula anterior</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-43_5342804a9d1e025758d5086b51bb75df">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>inseticida <span class="ot">&lt;-</span> InsectSprays</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>inseticida <span class="sc">|&gt;</span> </span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(spray)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  spray  n
1     A 12
2     B 12
3     C 12
4     D 12
5     E 12
6     F 12</code></pre>
</div>
</div>
<p>Como só temos um fator, a ANOVA neste caso seria unifatorial, com 6 níveis.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-44_dd53ac65ef18e8b9f3db3f350ad35ca3">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>inseticida <span class="sc">|&gt;</span> </span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(spray, count))<span class="sc">+</span></span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()<span class="sc">+</span></span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>()<span class="sc">+</span></span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Aula_06_07_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Observando os box, podemos inferir que as variâncias são heterogêneas. Tratamento com maior variabilidade (F), com menos variabilidade (C) e que possui outlier.</p>
<p>O modelo de ANOVA é ajustado, e trabalhamos com os resíduos da ANOVA, e não com os dados originais, e aí são aplicados os testes.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-45_ab3e91c0c72579403119d676c081f581">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(count <span class="sc">~</span> spray,</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> inseticida)</span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>m1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = count ~ spray, data = inseticida)

Coefficients:
(Intercept)       sprayB       sprayC       sprayD       sprayE       sprayF  
    14.5000       0.8333     -12.4167      -9.5833     -11.0000       2.1667  </code></pre>
</div>
</div>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-46_9fff7b7e312179a6eb781f248b4d3d2e">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = count ~ spray, data = inseticida)

Residuals:
   Min     1Q Median     3Q    Max 
-8.333 -1.958 -0.500  1.667  9.333 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  14.5000     1.1322  12.807  &lt; 2e-16 ***
sprayB        0.8333     1.6011   0.520    0.604    
sprayC      -12.4167     1.6011  -7.755 7.27e-11 ***
sprayD       -9.5833     1.6011  -5.985 9.82e-08 ***
sprayE      -11.0000     1.6011  -6.870 2.75e-09 ***
sprayF        2.1667     1.6011   1.353    0.181    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.922 on 66 degrees of freedom
Multiple R-squared:  0.7244,    Adjusted R-squared:  0.7036 
F-statistic:  34.7 on 5 and 66 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-47_5bb0e8cf8e769347e110b7fffbda502a">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: count
          Df Sum Sq Mean Sq F value    Pr(&gt;F)    
spray      5 2668.8  533.77  34.702 &lt; 2.2e-16 ***
Residuals 66 1015.2   15.38                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-48_555a2eb9104afb1ea890217d8fa85de2">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(m1<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Aula_06_07_files/figure-html/unnamed-chunk-48-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-49_531c4128ea569db4add7bdb6c4456605">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(m1<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  m1$residuals
W = 0.96006, p-value = 0.02226</code></pre>
</div>
</div>
<p>O h0 deste teste sugere que é normal. O Pvalor deste teste indica que é</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-50_75d98256b6597b04c328c66642ce9e0c">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(m1<span class="sc">$</span>residuals)</span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(m1<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Aula_06_07_files/figure-html/unnamed-chunk-50-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Quando os pontos acompanham a linha de tendência central, acusa que os dados são normais.</p>
<p>Premissa importante: tem maior peso na decisão - homocedasticidade.</p>
<section id="barlett-test" class="level3">
<h3 class="anchored" data-anchor-id="barlett-test">Barlett Test</h3>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-51_6aeb5083a52e5d656e38f64f27d8c8ee">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bartlett.test</span>(count <span class="sc">~</span> spray,</span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> inseticida)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Bartlett test of homogeneity of variances

data:  count by spray
Bartlett's K-squared = 25.96, df = 5, p-value = 9.085e-05</code></pre>
</div>
</div>
<p>Para testar a normalidade.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-52_0fbc21a447223ad18d58895f8ddf1f86">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_normality</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Warning: Non-normality of residuals detected (p = 0.022).</code></pre>
</div>
</div>
<p>Para testar heterocedasticidade.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-53_996bf1fbfeb57bebbf58d0e5e4385cf3">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_heteroscedasticity</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Warning: Heteroscedasticity (non-constant error variance) detected (p &lt; .001).</code></pre>
</div>
</div>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-54_a0be837999b2511b6f31b589f2f86c18">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">simulateResiduals</span>(m1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Aula_06_07_files/figure-html/unnamed-chunk-54-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Transformação de dados:</p>
<ul>
<li><p>Extrair a raiz quadrada (apropriada pra dados de contagem);</p></li>
<li><p>Outros métodos (procurar).</p></li>
</ul>
</section>
<section id="alternativa-01---extração-da-raiz-quadrada" class="level3">
<h3 class="anchored" data-anchor-id="alternativa-01---extração-da-raiz-quadrada">Alternativa 01 - Extração da Raiz quadrada</h3>
<p>Alternativa 01 - transformação</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-55_9ac26483f06e44b20d1d43e4825e0884">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a>inseticida <span class="ot">&lt;-</span>  inseticida <span class="sc">|&gt;</span> </span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">count2 =</span> <span class="fu">sqrt</span>(count))</span>
<span id="cb98-3"><a href="#cb98-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb98-4"><a href="#cb98-4" aria-hidden="true" tabindex="-1"></a>inseticida <span class="sc">|&gt;</span> </span>
<span id="cb98-5"><a href="#cb98-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(spray, count2))<span class="sc">+</span></span>
<span id="cb98-6"><a href="#cb98-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()<span class="sc">+</span></span>
<span id="cb98-7"><a href="#cb98-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>()<span class="sc">+</span></span>
<span id="cb98-8"><a href="#cb98-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Aula_06_07_files/figure-html/unnamed-chunk-55-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>A normalidade não é um problema aqui, e sim a variância.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-56_57fc5298789d1f4357b2e7fc639a5730">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(count2 <span class="sc">~</span> spray, </span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> inseticida)</span>
<span id="cb99-3"><a href="#cb99-3" aria-hidden="true" tabindex="-1"></a>m2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = count2 ~ spray, data = inseticida)

Coefficients:
(Intercept)       sprayB       sprayC       sprayD       sprayE       sprayF  
     3.7607       0.1160      -2.5158      -1.5963      -1.9512       0.2579  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_normality</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: residuals appear as normally distributed (p = 0.681).</code></pre>
</div>
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_homogeneity</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: There is not clear evidence for different variances across groups (Bartlett Test, p = 0.586).</code></pre>
</div>
</div>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-57_b775f38dc1459ec1256e7a85e62e85ad">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: count2
          Df Sum Sq Mean Sq F value    Pr(&gt;F)    
spray      5 88.438 17.6876  44.799 &lt; 2.2e-16 ***
Residuals 66 26.058  0.3948                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-58_ea614a66b565fcc8425e4668130b8502">
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(m2<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Aula_06_07_files/figure-html/unnamed-chunk-58-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-59_59764234fba4b11d38661c1c61e8f5e4">
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = count2 ~ spray, data = inseticida)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.24486 -0.39970 -0.01902  0.42661  1.40089 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   3.7607     0.1814  20.733  &lt; 2e-16 ***
sprayB        0.1160     0.2565   0.452    0.653    
sprayC       -2.5158     0.2565  -9.807 1.64e-14 ***
sprayD       -1.5963     0.2565  -6.223 3.80e-08 ***
sprayE       -1.9512     0.2565  -7.606 1.34e-10 ***
sprayF        0.2579     0.2565   1.006    0.318    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.6283 on 66 degrees of freedom
Multiple R-squared:  0.7724,    Adjusted R-squared:  0.7552 
F-statistic:  44.8 on 5 and 66 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-60_61d7e8639aa81ca8d5f1690e05cd5a54">
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(m2<span class="sc">$</span>residuals)</span>
<span id="cb110-2"><a href="#cb110-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(m2<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Aula_06_07_files/figure-html/unnamed-chunk-60-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>De acordo com o plot, é possível inferenciar que os problemas de normalidade foram resolvidos.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-61_0cf8ffc576ef870eb4436191eb5a3e08">
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(m2<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  m2$residuals
W = 0.98721, p-value = 0.6814</code></pre>
</div>
</div>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-62_86ca31e7d477c25ae1b25281e5b0a7e6">
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bartlett.test</span>(count2 <span class="sc">~</span> spray,</span>
<span id="cb113-2"><a href="#cb113-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span>inseticida)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Bartlett test of homogeneity of variances

data:  count2 by spray
Bartlett's K-squared = 3.7525, df = 5, p-value = 0.5856</code></pre>
</div>
</div>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-63_101547330666e1e2fb606688de98e4b9">
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_normality</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: residuals appear as normally distributed (p = 0.681).</code></pre>
</div>
</div>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-64_19373ee9819155b749a7d05b0ee80c85">
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_heteroscedasticity</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: Error variance appears to be homoscedastic (p = 0.854).</code></pre>
</div>
</div>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-65_5232c38a1e1c0cfd23bb71a5f5e3ec62">
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">simulateResiduals</span>(m2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Aula_06_07_files/figure-html/unnamed-chunk-65-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>É possível observar que a transformação dos dados resolveu a dispersão das variâncias. Podemos continuar com o teste. O resultado foi não significativo.</p>
<p>Podemos seguir com a estimativa das médias.</p>
<p>A ANOVA é um teste mais robusto à falta de normalidade do que à falta de homocedasticidade.</p>
<p>Levene test - undefined</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-66_06dc0582b4d9b5a0232d76cf6603590a">
<div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a>m1_medias <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(m1, <span class="sc">~</span>spray)</span>
<span id="cb120-2"><a href="#cb120-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(m1_medias)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Aula_06_07_files/figure-html/unnamed-chunk-66-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-67_ee466ee753a08b67f14941e083ed1376">
<div class="sourceCode cell-code" id="cb121"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cld</span>(m1_medias)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> spray emmean   SE df lower.CL upper.CL .group
 C       2.08 1.13 66   -0.177     4.34  1    
 E       3.50 1.13 66    1.240     5.76  1    
 D       4.92 1.13 66    2.656     7.18  1    
 A      14.50 1.13 66   12.240    16.76   2   
 B      15.33 1.13 66   13.073    17.59   2   
 F      16.67 1.13 66   14.406    18.93   2   

Confidence level used: 0.95 
P value adjustment: tukey method for comparing a family of 6 estimates 
significance level used: alpha = 0.05 
NOTE: If two or more means share the same grouping symbol,
      then we cannot show them to be different.
      But we also did not show them to be the same. </code></pre>
</div>
</div>
<p>Agora, para o conjunto de dados transformados.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-68_0b5d36ab249cb227cf86f874e945c8c5">
<div class="sourceCode cell-code" id="cb123"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a>m2_medias <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(m2, <span class="sc">~</span>spray)</span>
<span id="cb123-2"><a href="#cb123-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(m2_medias)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Aula_06_07_files/figure-html/unnamed-chunk-68-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-69_9e9fbf9dc6f83b9904f057a4078776c2">
<div class="sourceCode cell-code" id="cb124"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb124-1"><a href="#cb124-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cld</span>(m2_medias)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> spray emmean    SE df lower.CL upper.CL .group
 C       1.24 0.181 66    0.883     1.61  1    
 E       1.81 0.181 66    1.447     2.17  12   
 D       2.16 0.181 66    1.802     2.53   2   
 A       3.76 0.181 66    3.399     4.12    3  
 B       3.88 0.181 66    3.514     4.24    3  
 F       4.02 0.181 66    3.656     4.38    3  

Confidence level used: 0.95 
P value adjustment: tukey method for comparing a family of 6 estimates 
significance level used: alpha = 0.05 
NOTE: If two or more means share the same grouping symbol,
      then we cannot show them to be different.
      But we also did not show them to be the same. </code></pre>
</div>
</div>
<p>Com a média transformada, são criados 3 grupos, ou seja, a discriminação foi melhor, e com isso a comparação foi melhor.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-70_8b9ab9333a9fc4a10e19e27f7dc01283">
<div class="sourceCode cell-code" id="cb126"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb126-1"><a href="#cb126-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pwpm</span>(m2_medias)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       A      B      C      D      E      F
A [3.76] 0.9975 &lt;.0001 &lt;.0001 &lt;.0001 0.9145
B -0.116 [3.88] &lt;.0001 &lt;.0001 &lt;.0001 0.9936
C  2.516  2.632 [1.24] 0.0081 0.2513 &lt;.0001
D  1.596  1.712 -0.919 [2.16] 0.7366 &lt;.0001
E  1.951  2.067 -0.565  0.355 [1.81] &lt;.0001
F -0.258 -0.142 -2.774 -1.854 -2.209 [4.02]

Row and column labels: spray
Upper triangle: P values   adjust = "tukey"
Diagonal: [Estimates] (emmean) 
Lower triangle: Comparisons (estimate)   earlier vs. later</code></pre>
</div>
</div>
<p>As médias encontram-se na diagonal. Acima estão os valores de P valor para comparação das médias.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-71_21a2cca729e3967752503e60533b261c">
<div class="sourceCode cell-code" id="cb128"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb128-1"><a href="#cb128-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pwpp</span>(m2_medias)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Aula_06_07_files/figure-html/unnamed-chunk-71-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="alternativa-02---teste-não-paramétrico" class="level3">
<h3 class="anchored" data-anchor-id="alternativa-02---teste-não-paramétrico">Alternativa 02 - teste não paramétrico</h3>
<p>O teste não paramétrico leva em consideração os valores originais, sem transformação.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-72_6febb3b684989743f9da28ced5de3026">
<div class="sourceCode cell-code" id="cb129"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kruskal.test</span>(count <span class="sc">~</span> spray,</span>
<span id="cb129-2"><a href="#cb129-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> inseticida)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  count by spray
Kruskal-Wallis chi-squared = 54.691, df = 5, p-value = 1.511e-10</code></pre>
</div>
</div>
<p>Hipótese nula = as médias são iguais.</p>
<p>Rejeita-se a hipótese nula, porque o P é menor que 0,05.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-73_ee96c590828b6b7b354b4bfbc333d965">
<div class="sourceCode cell-code" id="cb131"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb131-1"><a href="#cb131-1" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">kruskal</span>(inseticida<span class="sc">$</span>count,</span>
<span id="cb131-2"><a href="#cb131-2" aria-hidden="true" tabindex="-1"></a>        inseticida<span class="sc">$</span>spray,</span>
<span id="cb131-3"><a href="#cb131-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">group =</span> <span class="cn">TRUE</span>)</span>
<span id="cb131-4"><a href="#cb131-4" aria-hidden="true" tabindex="-1"></a>m3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$statistics
     Chisq Df      p.chisq  t.value      MSD
  54.69134  5 1.510845e-10 1.996564 8.462804

$parameters
            test p.ajusted           name.t ntr alpha
  Kruskal-Wallis      none inseticida$spray   6  0.05

$means
  inseticida.count     rank      std  r Min Max   Q25  Q50   Q75
A        14.500000 52.16667 4.719399 12   7  23 11.50 14.0 17.75
B        15.333333 54.83333 4.271115 12   7  21 12.50 16.5 17.50
C         2.083333 11.45833 1.975225 12   0   7  1.00  1.5  3.00
D         4.916667 25.58333 2.503028 12   2  12  3.75  5.0  5.00
E         3.500000 19.33333 1.732051 12   1   6  2.75  3.0  5.00
F        16.666667 55.62500 6.213378 12   9  26 12.50 15.0 22.50

$comparison
NULL

$groups
  inseticida$count groups
F         55.62500      a
B         54.83333      a
A         52.16667      a
D         25.58333      b
E         19.33333     bc
C         11.45833      c

attr(,"class")
[1] "group"</code></pre>
</div>
</div>
<p>Este comando utiliza o teste Fisher. Utiliza o ranking criado para calcular a estatística de agrupamento.</p>
<p>O teste não paramétrico trouxe o mesmo resultado que o teste paramétrico transformado (extraindo a raiz).</p>
</section>
<section id="alternativa-03---glms" class="level3">
<h3 class="anchored" data-anchor-id="alternativa-03---glms">Alternativa 03 - GLMs</h3>
<p>Usa uma estatística mais moderna, não levando em conta se a distribuição é normal. Usa a distribuição de Poisson.</p>
<p>O teste generalizado é mais aceito e estudado por trabalhar os dados originais. É uma forma mais “elegante” de trabalhar os dados.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-74_40b90a21082c794c01733b467633c77c">
<div class="sourceCode cell-code" id="cb133"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb133-1"><a href="#cb133-1" aria-hidden="true" tabindex="-1"></a>m4 <span class="ot">&lt;-</span> <span class="fu">glm</span>(count <span class="sc">~</span> spray,</span>
<span id="cb133-2"><a href="#cb133-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">family =</span> poisson,</span>
<span id="cb133-3"><a href="#cb133-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">data =</span> inseticida)</span>
<span id="cb133-4"><a href="#cb133-4" aria-hidden="true" tabindex="-1"></a>m4</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:  glm(formula = count ~ spray, family = poisson, data = inseticida)

Coefficients:
(Intercept)       sprayB       sprayC       sprayD       sprayE       sprayF  
    2.67415      0.05588     -1.94018     -1.08152     -1.42139      0.13926  

Degrees of Freedom: 71 Total (i.e. Null);  66 Residual
Null Deviance:      409 
Residual Deviance: 98.33    AIC: 376.6</code></pre>
</div>
</div>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-75_b84c706eb9b25bb9214417f73640d6fa">
<div class="sourceCode cell-code" id="cb135"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb135-1"><a href="#cb135-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = count ~ spray, family = poisson, data = inseticida)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  2.67415    0.07581  35.274  &lt; 2e-16 ***
sprayB       0.05588    0.10574   0.528    0.597    
sprayC      -1.94018    0.21389  -9.071  &lt; 2e-16 ***
sprayD      -1.08152    0.15065  -7.179 7.03e-13 ***
sprayE      -1.42139    0.17192  -8.268  &lt; 2e-16 ***
sprayF       0.13926    0.10367   1.343    0.179    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 409.041  on 71  degrees of freedom
Residual deviance:  98.329  on 66  degrees of freedom
AIC: 376.59

Number of Fisher Scoring iterations: 5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb137"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb137-1"><a href="#cb137-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(m4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table (Type II tests)

Response: count
      LR Chisq Df Pr(&gt;Chisq)    
spray   310.71  5  &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-76_bcd79b75716d61af0460a4f0a02ee521">
<div class="sourceCode cell-code" id="cb139"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb139-1"><a href="#cb139-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">simulateResiduals</span>(m4))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Aula_06_07_files/figure-html/unnamed-chunk-76-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-77_07e63f32f35a5ed2fb30bce36c6580f6">
<div class="sourceCode cell-code" id="cb140"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb140-1"><a href="#cb140-1" aria-hidden="true" tabindex="-1"></a>m4_medias <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(m4, <span class="sc">~</span> spray,</span>
<span id="cb140-2"><a href="#cb140-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb140-3"><a href="#cb140-3" aria-hidden="true" tabindex="-1"></a>m4_medias</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> spray  rate    SE  df asymp.LCL asymp.UCL
 A     14.50 1.099 Inf     12.50     16.82
 B     15.33 1.130 Inf     13.27     17.72
 C      2.08 0.417 Inf      1.41      3.08
 D      4.92 0.640 Inf      3.81      6.35
 E      3.50 0.540 Inf      2.59      4.74
 F     16.67 1.179 Inf     14.51     19.14

Confidence level used: 0.95 
Intervals are back-transformed from the log scale </code></pre>
</div>
</div>
<p>O intervalo indica que 95% das vezes a média se encontra dentro do intervalo.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-78_c17c58e2a71c53b71a90fc110d439d8c">
<div class="sourceCode cell-code" id="cb142"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb142-1"><a href="#cb142-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cld</span>(m4_medias)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> spray  rate    SE  df asymp.LCL asymp.UCL .group
 C      2.08 0.417 Inf      1.41      3.08  1    
 E      3.50 0.540 Inf      2.59      4.74  12   
 D      4.92 0.640 Inf      3.81      6.35   2   
 A     14.50 1.099 Inf     12.50     16.82    3  
 B     15.33 1.130 Inf     13.27     17.72    3  
 F     16.67 1.179 Inf     14.51     19.14    3  

Confidence level used: 0.95 
Intervals are back-transformed from the log scale 
P value adjustment: tukey method for comparing a family of 6 estimates 
Tests are performed on the log scale 
significance level used: alpha = 0.05 
NOTE: If two or more means share the same grouping symbol,
      then we cannot show them to be different.
      But we also did not show them to be the same. </code></pre>
</div>
</div>
<p>Este teste também separa em 3 grupos, da mesma forma que os dados transformados. Só que aqui, os dados são originais.</p>
</section>
<section id="transformação-box-cox" class="level2">
<h2 class="anchored" data-anchor-id="transformação-box-cox">Transformação Box-Cox</h2>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-79_311126c00a78cbcd710591901c206ff9">
<div class="sourceCode cell-code" id="cb144"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb144-1"><a href="#cb144-1" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">boxcox</span>(<span class="fu">lm</span>(inseticida<span class="sc">$</span>count<span class="fl">+0.1</span> <span class="sc">~</span><span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Aula_06_07_files/figure-html/unnamed-chunk-79-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-80_2088bcef195fc3f81f324a04f6155f64">
<div class="sourceCode cell-code" id="cb145"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb145-1"><a href="#cb145-1" aria-hidden="true" tabindex="-1"></a>lambda <span class="ot">&lt;-</span> b<span class="sc">$</span>x[<span class="fu">which.max</span>(b<span class="sc">$</span>y)]</span>
<span id="cb145-2"><a href="#cb145-2" aria-hidden="true" tabindex="-1"></a>lambda</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4242424</code></pre>
</div>
</div>
<p>Criando a variável transformada.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-81_13700014586e3a7e2ffb2922ae04045e">
<div class="sourceCode cell-code" id="cb147"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb147-1"><a href="#cb147-1" aria-hidden="true" tabindex="-1"></a>inseticida<span class="sc">$</span>count3 <span class="ot">&lt;-</span> (inseticida<span class="sc">$</span>count <span class="sc">^</span> lambda <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">/</span> lambda</span>
<span id="cb147-2"><a href="#cb147-2" aria-hidden="true" tabindex="-1"></a>inseticida<span class="sc">$</span>count3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  3.903635  3.024469  6.043993  4.864268  4.864268  4.407118  3.903635
 [8]  6.557185  5.484274  6.043993  4.864268  4.640760  4.161975  5.484274
[15]  6.219699  4.161975  5.285168  4.864268  5.484274  5.484274  5.863153
[22]  6.219699  3.024469  4.640760 -2.357143  0.000000  3.024469  0.805831
[29]  1.399509  0.000000  0.805831  0.000000  1.399509 -2.357143  0.000000
[36]  1.887150  1.399509  2.308577  4.407118  2.683787  1.887150  1.399509
[43]  2.308577  2.308577  2.308577  2.308577  0.805831  1.887150  1.399509
[50]  2.308577  1.399509  2.308577  1.399509  2.683787  0.000000  0.000000
[57]  1.399509  0.805831  2.683787  1.887150  4.161975  3.629951  5.078760
[64]  6.390651  5.078760  5.285168  4.640760  3.903635  7.033117  7.033117
[71]  6.719601  4.640760</code></pre>
</div>
</div>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-82_dbc8bcd959287ffe805fe29754936392">
<div class="sourceCode cell-code" id="cb149"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb149-1"><a href="#cb149-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(inseticida<span class="sc">$</span>count)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Aula_06_07_files/figure-html/unnamed-chunk-82-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="parte-02---aula-07" class="level3">
<h3 class="anchored" data-anchor-id="parte-02---aula-07">Parte 02 - aula 07</h3>
<p>Aplicação de Anova fatorial 2x2</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-83_fa381c83cc2ec5dfbef2d314c7406dfb">
<div class="sourceCode cell-code" id="cb150"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb150-1"><a href="#cb150-1" aria-hidden="true" tabindex="-1"></a>li <span class="ot">&lt;-</span> <span class="fu">gsheet2tbl</span>(<span class="st">"https://docs.google.com/spreadsheets/d/1bq2N19DcZdtax2fQW9OHSGMR0X2__Z9T/edit#gid=2023059672"</span>)</span>
<span id="cb150-2"><a href="#cb150-2" aria-hidden="true" tabindex="-1"></a>li</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 8
   treat         dose   rep  n_sp dis_sp n_seeds inf_seeds severity
   &lt;chr&gt;        &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
 1 Ionic liquid   0.5     1   103     13      25        10   0.126 
 2 Ionic liquid   0.5     2   125     31      25        12   0.248 
 3 Ionic liquid   0.5     3   210     80      25        12   0.381 
 4 Ionic liquid   0.5     4    97     28      25        10   0.289 
 5 Ionic liquid   0.5     5   180     75      25        11   0.417 
 6 Ionic liquid   2       2   116      9      25         6   0.0776
 7 Ionic liquid   2       3   166      7      25         3   0.0422
 8 Ionic liquid   2       4   157     12      25         1   0.0764
 9 Ionic liquid   2       5   129      7      25         7   0.0543
10 Ionic liquid   2       1    84      0      25         1   0     
11 Tebuconazole   0.5     1   121      0      25         2   0     
12 Tebuconazole   0.5     2   123      6      25         5   0.0488
13 Tebuconazole   0.5     3   107      3      25         1   0.0280
14 Tebuconazole   0.5     4    90      0      25         2   0     
15 Tebuconazole   0.5     5   142      4      25         1   0.0282
16 Tebuconazole   2       1   166      3      25         5   0.0181
17 Tebuconazole   2       2   120      0      25         2   0     
18 Tebuconazole   2       3   100      4      25         2   0.04  
19 Tebuconazole   2       4    96      3      25         0   0.0312
20 Tebuconazole   2       5   170      2      25         4   0.0118</code></pre>
</div>
</div>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-84_4372559c921cf77c2459b07b7971d5a4">
<div class="sourceCode cell-code" id="cb152"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb152-1"><a href="#cb152-1" aria-hidden="true" tabindex="-1"></a>sev <span class="ot">&lt;-</span> li <span class="sc">|&gt;</span> </span>
<span id="cb152-2"><a href="#cb152-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(dose, severity, <span class="at">color =</span> <span class="fu">factor</span>(dose)))<span class="sc">+</span></span>
<span id="cb152-3"><a href="#cb152-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.1</span>)<span class="sc">+</span></span>
<span id="cb152-4"><a href="#cb152-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>treat)<span class="sc">+</span></span>
<span id="cb152-5"><a href="#cb152-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb152-6"><a href="#cb152-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb152-7"><a href="#cb152-7" aria-hidden="true" tabindex="-1"></a>sev</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Aula_06_07_files/figure-html/unnamed-chunk-84-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>O gráfico mostra que a dose 2 do líquido iônico reduziu a severidade da doença semelhantemente às doses de fungicidas aplicados no outro nível de fator (tebuconazol). Para próximos experimentos poderiam ser realizados outros níveis do fator líquido iônico.</p>
</section>
<section id="modelo-fatorial-two-way-anova" class="level3">
<h3 class="anchored" data-anchor-id="modelo-fatorial-two-way-anova">Modelo Fatorial (two-way ANOVA)</h3>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-85_54d8aae26e8ca8e61420cbed28f50fb9">
<div class="sourceCode cell-code" id="cb153"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb153-1"><a href="#cb153-1" aria-hidden="true" tabindex="-1"></a>mf <span class="ot">&lt;-</span> <span class="fu">lm</span>(severity <span class="sc">~</span> treat<span class="sc">*</span><span class="fu">factor</span>(dose),</span>
<span id="cb153-2"><a href="#cb153-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> li)</span>
<span id="cb153-3"><a href="#cb153-3" aria-hidden="true" tabindex="-1"></a>mf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = severity ~ treat * factor(dose), data = li)

Coefficients:
                    (Intercept)                treatTebuconazole  
                         0.2921                          -0.2711  
                  factor(dose)2  treatTebuconazole:factor(dose)2  
                        -0.2420                           0.2412  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb155"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb155-1"><a href="#cb155-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: severity
                   Df   Sum Sq  Mean Sq F value    Pr(&gt;F)    
treat               1 0.113232 0.113232  30.358 4.754e-05 ***
factor(dose)        1 0.073683 0.073683  19.755 0.0004077 ***
treat:factor(dose)  1 0.072739 0.072739  19.502 0.0004326 ***
Residuals          16 0.059678 0.003730                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Aparecem mais duas linhas: dose, e interação tratamento:dose.</p>
<p>Ocorre uma interação significativa. Devemos estimar as médias de um dentro do outro, ou seja, a combinação dos tratamentos. As médias devem ser estimadas pelas interações significativas, devem ser decompostas para haver comparação.</p>
<p>Letras maiúsculas comparam as colunas, letras minúsculas comparam as linhas.</p>
<section id="testando-as-premissas" class="level4">
<h4 class="anchored" data-anchor-id="testando-as-premissas">Testando as premissas</h4>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-86_64c58544f0d6abf44d3cffc7628ccb34">
<div class="sourceCode cell-code" id="cb157"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb157-1"><a href="#cb157-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">simulateResiduals</span>(mf))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Aula_06_07_files/figure-html/unnamed-chunk-86-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-87_b80ed9c3ddc8a32c8f0ddf6ce861d0ad">
<div class="sourceCode cell-code" id="cb158"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb158-1"><a href="#cb158-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_normality</span>(mf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Warning: Non-normality of residuals detected (p = 0.011).</code></pre>
</div>
</div>
<p>Estimar as médias do fungicida para cada dose.</p>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-88_0964152fa725c9f403900be2146fe650">
<div class="sourceCode cell-code" id="cb160"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb160-1"><a href="#cb160-1" aria-hidden="true" tabindex="-1"></a>mf_medias <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(mf, <span class="sc">~</span> treat <span class="sc">|</span> dose)</span>
<span id="cb160-2"><a href="#cb160-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cld</span>(mf_medias)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>dose = 0.5:
 treat        emmean     SE df lower.CL upper.CL .group
 Tebuconazole 0.0210 0.0273 16 -0.03690   0.0789  1    
 Ionic liquid 0.2921 0.0273 16  0.23420   0.3500   2   

dose = 2.0:
 treat        emmean     SE df lower.CL upper.CL .group
 Tebuconazole 0.0202 0.0273 16 -0.03768   0.0781  1    
 Ionic liquid 0.0501 0.0273 16 -0.00781   0.1080  1    

Confidence level used: 0.95 
significance level used: alpha = 0.05 
NOTE: If two or more means share the same grouping symbol,
      then we cannot show them to be different.
      But we also did not show them to be the same. </code></pre>
</div>
</div>
<div class="cell" data-hash="Aula_06_07_cache/html/unnamed-chunk-89_9b54259e791f5e8fa17bec7451562132">
<div class="sourceCode cell-code" id="cb162"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb162-1"><a href="#cb162-1" aria-hidden="true" tabindex="-1"></a>mf_medias <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(mf, <span class="sc">~</span> dose <span class="sc">|</span> treat)</span>
<span id="cb162-2"><a href="#cb162-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cld</span>(mf_medias)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>treat = Ionic liquid:
 dose emmean     SE df lower.CL upper.CL .group
  2.0 0.0501 0.0273 16 -0.00781   0.1080  1    
  0.5 0.2921 0.0273 16  0.23420   0.3500   2   

treat = Tebuconazole:
 dose emmean     SE df lower.CL upper.CL .group
  2.0 0.0202 0.0273 16 -0.03768   0.0781  1    
  0.5 0.0210 0.0273 16 -0.03690   0.0789  1    

Confidence level used: 0.95 
significance level used: alpha = 0.05 
NOTE: If two or more means share the same grouping symbol,
      then we cannot show them to be different.
      But we also did not show them to be the same. </code></pre>
</div>
</div>
<p>As duas tabelas acima indicam as letras para difenrenciação das médias.</p>
<table class="table">
<thead>
<tr class="header">
<th>Tratamento</th>
<th>0,5</th>
<th>2,0</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>LI</td>
<td>0,29 Aa</td>
<td>0,05 Ab</td>
</tr>
<tr class="even">
<td>TEB</td>
<td>0,02 Ba</td>
<td>0,02 Aa</td>
</tr>
</tbody>
</table>


</section>
</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>